### ISSUE TITLE
HP-SOCKET项目结构建议

### ISSUE THREAD

**Issue by lion117** [ldcsaa/HP-Socket#10]
# 问题
> 感觉目前的项目文件结构不甚方便, 建议对项目文件的结构进行一定的调整

# 建议点
1. 作为库, include , libs , bin, demo等放置在根目录下
> 这方方便快速调用. 下载更新库的时候, 对项目的改动也少. 如果需要自己生成静态库, 也可以只需要把生成的lib放置到目录下即可. 可以最大限度的减小对源项目的改动
2. 建议提供可编译生成静态库的项目. 可减少软件编译时间, 同时利于工具型软件发布（无需携带dll）

**Comment by ldcsaa** [comment]
Thanks~ 很好的建议。下个版本或Linux版会调整目录结构。

**Comment by wangxuefei123** [comment]
Linux版本在哪个目录？

**Comment by ldcsaa** [comment]
Linux版还没写完，先发个 SSL 版再说。
