### ISSUE TITLE
关于添加定时器

### ISSUE THREAD

**Issue by blackhat-a** [ldcsaa/HP-Socket#101]
如果我有一个定时任务，那应该怎么加呢？即我想添加一个定时器回调
因为run之后就死循环了，希望能指点下

**Comment by blackhat-a** [comment]
CIOHandler ontimer 是如何添加定时任务的？没看到实例代码

**Comment by ldcsaa** [comment]
1、IODispatcher 的 OnTimer 定时器的定时设置通过Start()方法最后一个参数传入，但该定时器用于执行简单任务（不能死循环），因此不适合你的需求。
2、IODispatcher 当然也支持大规模定时器，就是把定时器对象注册到epoll，参考 ArqHelper.h，这也不是你需要的场景。
3、你的场景其实很简单：开启一个后台现场，在死循环中执行执行任务，可以参考 CHttpServerT::CleanerThreadProc() 线程，定时清理过期连接。
4、HP的Event.h 中提供一个poll模型定时器 CTimerEvent，使用起来也十分简单。
