### ISSUE TITLE
多线程：CIODispatcher::WorkerProc

### ISSUE THREAD

**Issue by blackhat-a** [ldcsaa/HP-Socket#102]
多线程执行这个函数的时候会有同步问题吧？m_epoll 应该是多个线程共享的，为什么不需要加锁呢？

m_pHandler 里面的业务逻辑也得加锁处理吧？因为有可能多个通信线程在执行

多谢大神指导一下，准备加个定时器，但是多线程好像有点麻烦，如果是单线程，像redis那样就好处理，多线程有点糊涂了

**Comment by blackhat-a** [comment]
如果两个数据包刚好在不同的线程处理，监听者处理的时候，可能会有同步问题吧，可能处理了一个数据包的一般逻辑业务就开始执行另外一个数据包的逻辑，可能是同一个函数，同一个变量

**Comment by ldcsaa** [comment]
不会出问题

**Comment by blackhat-a** [comment]
好的
