### ISSUE TITLE
windows版本不能在xp上运行

### ISSUE THREAD

**Issue by wang70937** [ldcsaa/HP-Socket#108]
vs2017编译hp-socket后，在xp上运行报错：
![image](https://user-images.githubusercontent.com/919848/75505824-436a2980-5a17-11ea-9347-be842f394701.png)

看msdn上说 ReleaseSRWLockExclusive 最小支持的版本是vista。
怎样替代这些api支持xp？

**Comment by ldcsaa** [comment]
以下几个方法供选择：
1、用hp发布包自带dll
2、用vs2015或以下版本编译
3、修改 Common/Src/GeneralHelper.h 宏定义
