### ISSUE TITLE
centos 6.10 编译不过

### ISSUE THREAD

**Issue by blackhat-a** [ldcsaa/HP-Socket#109]
系统：CentOS release 6.10 (Final)
内核：2.6.32-754.3.5.el6.x86_64
glibc:  GLIBC_2.14
gcc/g++: 5.2.0
最后一步报错，搞一天也不行, 最后一步链接出问题，求大牛解答一下，谢谢
/usr/bin/ld: BFD version 2.20.51.0.2-5.48.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

**Comment by ldcsaa** [comment]
https://github.com/laurenz/oracle_fdw/issues/185

升级一下gcc版本试试

**Comment by blackhat-a** [comment]
gcc 5.4.0 + ld 2.26.1 才能编译，但是还是要禁止 jemalloc, 和 libcrypto
dependent/x64/lib/libjemalloc_pic.a(jemalloc.pic.o): In function `malloc_conf_init_helper':
jemalloc.c:(.text+0x1930): undefined reference to `secure_getenv'
dependent/x64/lib/libcrypto.a(getenv.o): In function `ossl_safe_getenv':
getenv.c:(.text+0x1): undefined reference to `secure_getenv'
不知道和解？
openssl也是有安装的，标准库是5.4.0的

**Comment by blackhat-a** [comment]
centos 6.10 没有这个函数，ubuntu才有这个函数？

**Comment by ldcsaa** [comment]
jemalloc 用 gcc6 编译的
