### ISSUE TITLE
关于linux配置的问题 

### ISSUE THREAD

**Issue by piaominhao** [ldcsaa/HP-Socket#112]
1>g++ : error : /home/sp2/MyWork/HP-Socket/Linux/demo/testecho/server/../../Global/helper.cpp: No such file or directory
1>g++ : warning : ‘-x c++’ after last input file has no effect
1>g++ : error : no input files
1>g++ : error : compilation terminated.
不知道是哪里错了 怎么解决啊？ linux虚拟机里面有这个文件啊

**Comment by ldcsaa** [comment]
你用 _compile.sh_ 脚本编译吧，VS编译不好配置。
