### ISSUE TITLE
centos 6 运行崩溃

### ISSUE THREAD

**Issue by blackhat-a** [ldcsaa/HP-Socket#114]
环境 centos6, gcc 5.4.0 + ld 2.26.1 （用ubuntu, gcc 5.4.0 + ld 2.26.1 正常）
运行demo崩溃，编译没有问题
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/52157883/78743743-0daf4d80-7992-11ea-8cd1-4fd839c1fd0a.png">
./pull_server -b 127.0.0.1 -p 7989
输入start后崩溃，还没start之前没有问题

**Comment by blackhat-a** [comment]
centos 升级 gcc version 6.5.0 (GCC) 会一样的崩溃，难道只能用ubuntu系统吗

**Comment by blackhat-a** [comment]
./compile.sh -j false -s false
应该跟这个编译选项有关，这样编译，在ubuntu也会崩溃，可以断定是代码的bug，不是环境的问题
麻烦楼主看看

**Comment by ldcsaa** [comment]
Start 怎么会触发 FireReceive 事件？

**Comment by blackhat-a** [comment]
楼主你好，用的是官方demo，没改动过呢

**Comment by ldcsaa** [comment]
再好好研究吧！
