### ISSUE TITLE
Incorrect path to common libs

### ISSUE THREAD

**Issue by eugene-korobko** [ldcsaa/HP-Socket#115]
Paths to common libraries like 
`..\..\Common\Lib\openssl\$(VisualStudioVersion)\x86\lib`
Is incorrect, $(PlatformToolset) or $(PlatformToolsetVersion) should be used instead

VisualStudio is just an IDE, if open VS2010 project in VS2017 without upgrading, it will build source with 10 toolset and link with openssl for 17 version

**Comment by ldcsaa** [comment]
Please use the corresponding VS solution provided by the release package.
vs 2010, 2015, 2017, 2019.
