### ISSUE TITLE
static library link error

### ISSUE THREAD

**Issue by jjqcat** [ldcsaa/HP-Socket#116]
1>正在生成代码...
1>msvcrt.lib(initializers.obj) : warning LNK4098: 默认库“libcmt.lib”与其他库的使用冲突；请使用 /NODEFAULTLIB:library
1>CodelessSimWnd.obj : error LNK2001: 无法解析的外部符号 __imp_HP_Create_TcpPackServer
1>CodelessSimWnd.obj : error LNK2001: 无法解析的外部符号 __imp_HP_Destroy_TcpPackServer
1>.\bin/AGVControl.exe : fatal error LNK1120: 2 个无法解析的外部命令
1>已完成生成项目“AGVControl.vcxproj”的操作 - 失败。
========== 全部重新生成: 成功 0 个，失败 1 个，跳过 0 个 ==========

**Comment by ldcsaa** [comment]
项目配置问题，自行解决。
