### ISSUE TITLE
使用编译出错

### ISSUE THREAD

**Issue by blackhat-a** [ldcsaa/HP-Socket#118]
hp-socket-5.7.1\windows\common\src\PrivateHeap.h(126): error C2039: “bad_alloc”: 不是“std”的成员
hp-socket-5.7.1\windows\common\src\PrivateHeap.h(126): error C3861: “bad_alloc”: 找不到标识符
hp-socket-5.7.1\windows\common\src\PrivateHeap.h(143): error C2039: “bad_alloc”: 不是“std”的成员
hp-socket-5.7.1\windows\common\src\PrivateHeap.h(143): error C3861: “bad_alloc”: 找不到标识符

好奇怪，单独编译没有问题，在其他工程使用出问题了

**Comment by faholi** [comment]
看这个错误，应该是你没有#include 相关的依赖项
可参考：
https://blog.csdn.net/friendan/article/details/91308804
https://ask.csdn.net/questions/229056?sort=id
希望能解决你的问题

**Comment by blackhat-a** [comment]
你好，是的，必须在前面加一个include
#include <exception>
#include "../../../../../Src/HttpServer.h"
这样就没问题了，不过为什么这个库自己不加呢？
