### ISSUE TITLE
参数检查失败

### ISSUE THREAD

**Issue by blackhat-a** [ldcsaa/HP-Socket#119]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/52157883/81772856-82d5eb80-9519-11ea-8a7e-f910b855a34d.png">
啥参数都没设置过，正常的使用，却监听不成功，跟demo一样初始化的

**Comment by blackhat-a** [comment]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/52157883/81773965-190b1100-951c-11ea-9a0d-238d7efa800f.png">
初始化了，但是数值不对，为什么呢？我是这样用的：(指针对象)
     m_pListener = new CHttpServerListenerImpl(HTTP_NAME);
    m_pHttpserver = new CHttpServer(m_pListener);
在linux下面是ok的

**Comment by blackhat-a** [comment]
windows 平台下太难用了，用lib工程呢，出现刚刚的问题，将hpsocket的代码加入其他工程各种编译不过，各种莫名其妙的问题，要发疯的节奏

**Comment by blackhat-a** [comment]
使用 Unicode 字符集 我的工程是用unicode的，然后hpsocket也用unicode，就有这样的问题，hpsocket用多字节的话，链接不成功，是不是这个unicode问题引起的？

**Comment by ldcsaa** [comment]
好好看文档，好好看demo

**Comment by blackhat-a** [comment]
HPSOCKET_STATIC_LIB 这个已经加了，感觉初始化不成功，那些值没有被初始化，另外demo的链接也没有链接什么，跟文档不一致，编译是没有问题，初始化感觉是有问题，不知道是不是模版的原因，我用其他静态库也没这样初始化不成功的，求指点一下

**Comment by blackhat-a** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/52157883/81908210-85107680-95fb-11ea-8dcd-3e4fc6c073a9.png">

<img width="730" alt="image" src="https://user-images.githubusercontent.com/52157883/81908170-71fda680-95fb-11ea-9093-f40d19f59f51.png">

上面就是我的简单初始化，也没做啥复杂的东西，跟demo一样，就是失败

**Comment by longlong2132** [comment]
加群 来群里问吧 q群44636872 怪兽乐园------------------ 原始邮件 ------------------
发件人: "blackhat-a"<notifications@github.com>
发送时间: 2020年5月14日(星期四) 下午3:58
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [ldcsaa/HP-Socket] 参数检查失败 (#119)




 

 

 
上面就是我的简单初始化，也没做啥复杂的东西，跟demo一样，就是失败
 
&mdash;

**Comment by longlong2132** [comment]
检查一下dll ------------------ 原始邮件 ------------------
发件人: "blackhat-a"<notifications@github.com>
发送时间: 2020年5月14日(星期四) 下午3:58
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [ldcsaa/HP-Socket] 参数检查失败 (#119)




 

 

 
上面就是我的简单初始化，也没做啥复杂的东西，跟demo一样，就是失败
 
&mdash;

**Comment by ldcsaa** [comment]
代码发出来
