### ISSUE TITLE
Qt下一下监听失败

### ISSUE THREAD

**Issue by yanche521** [ldcsaa/HP-Socket#121]
在Qt下一下监听失败，是怎么回事：
1.写了一个类继承自CUDPServerListener，实现了对应的虚函数
2.写了一个类，初始化的时候，创建了CUDPArqServerPtr:
CUDPArqServerPtr * m_ptr = new CUDPArqServerPtr(&m_listerner);
然后调用 bool _ret = m_prt->Get()->Start("0.0.0.0", 20211);
结果，_ret变量返回的总是false，不明白怎么解决，查看了一下错误码是3，就是创建SOCKET失败。
不知道问题出在那哪里了？

**Comment by yanche521** [comment]
1.写了一个类继承自CUDPServerListener，实现了对应的虚函数
2.写了一个类，初始化的时候，创建了CUDPArqServerPtr:
CUDPArqServerPtr * m_ptr = new CUDPArqServerPtr(&m_listerner);
然后调用 bool _ret = m_prt->Get()->Start("0.0.0.0", 20211);

**Comment by hhbusui** [comment]
@yanche521  请问怎么解决的呢 我用UDP组播遇到了相似的问题， CUdpCastListener

**Comment by Endt4sk** [comment]
是不是用了Unicode的lib，而你的监听地址传的非Unicode字符串

**Comment by hhbusui** [comment]
这个一说 的确是这样的 多谢 @Endt4sk
