### ISSUE TITLE
Qt下Server一直Start失败

### ISSUE THREAD

**Issue by yanche521** [ldcsaa/HP-Socket#122]
1.写了一个类继承自CUDPServerListener，实现了对应的虚函数
2.写了另外一个类，在类的初始化的时候，创建了CUDPArqServerPtr:
CUDPArqServerPtr * m_ptr = new CUDPArqServerPtr(&m_listerner);
然后调用 bool _ret = m_prt->Get()->Start("0.0.0.0", 20211);
变量_ret一直返回失败，检测到错误码是3，也就是说创建SOCKET失败，不知道什么原因

希望作者能指点一下，感谢

**Comment by 844655441** [comment]
我之前也遇到这个问题，应该是你用的库版本，和QT的字符集版本不一致。例如你QT设置为unicode字符集，然后用hp的unicode库，就可以了。


 
---原始邮件---
发件人: "yanche521"<notifications@github.com&gt;
发送时间: 2020年5月21日 14:03:55
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ldcsaa/HP-Socket] Qt下Server一直Start失败 (#122)




 
1.写了一个类继承自CUDPServerListener，实现了对应的虚函数
 2.写了另外一个类，在类的初始化的时候，创建了CUDPArqServerPtr:
 CUDPArqServerPtr * m_ptr = new CUDPArqServerPtr(&amp;m_listerner);
 然后调用 bool _ret = m_prt-&gt;Get()-&gt;Start("0.0.0.0", 20211);
 变量_ret一直返回失败，检测到错误码是3，也就是说创建SOCKET失败，不知道什么原因
 
希望作者能指点一下，感谢

**Comment by yanche521** [comment]
> 我之前也遇到这个问题，应该是你用的库版本，和QT的字符集版本不一致。例如你QT设置为unicode字符集，然后用hp的unicode库，就可以了。
> …

好的，谢谢你，感谢

**Comment by yanche521** [comment]
> 我之前也遇到这个问题，应该是你用的库版本，和QT的字符集版本不一致。例如你QT设置为unicode字符集，然后用hp的unicode库，就可以了。
> …

为啥用了UDPArq，接收和发送的数据有粘包的问题

**Comment by ldcsaa** [comment]
UDP ARQ 不可能粘包
