### ISSUE TITLE
windows SSL通信失败

### ISSUE THREAD

**Issue by ugenehan** [ldcsaa/HP-Socket#125]
用工程里面的TestEcho-SSL这个的demo的sever、client可以正常通信。
然后我自己使用hp socket dll写了一个client的demo，可以正常连接，但是send的时候失败。GetLastErrorDesc()返回的是success。
GetLastError()返回的是5023

**Comment by ugenehan** [comment]
`

class CssldemoDlg : public CDialogEx,public ITcpClientListener
{
	CSSLClientPtr client_;
}

CssldemoDlg::CssldemoDlg(CWnd* pParent /*=NULL*/)
	: CDialogEx(CssldemoDlg::IDD, pParent),client_(this)
{
	m_hIcon = AfxGetApp()->LoadIcon(IDR_MAINFRAME);
}

void CssldemoDlg::OnBnClickedButton1()
{
	// TODO: 在此添加控件通知处理程序代码
	client_->CleanupSSLContext();
	BOOL ret = FALSE;

	ret = client_->SetupSSLContext(SSL_VM_PEER | SSL_VM_FAIL_IF_NO_PEER_CERT, 
		L"C:\\Users\\Administrator\\Desktop\\ssldemo\\Debug\\client.crt",
		L"C:\\Users\\Administrator\\Desktop\\ssldemo\\Debug\\client.key",
		L"123456",
		L"C:\\Users\\Administrator\\Desktop\\ssldemo\\Debug\\ca.crt");
	if (!ret)
	{
		::MessageBoxW(0,client_->GetLastErrorDesc(),L"err",3);
		return;
	}

	ret = client_->Start(L"127.0.0.1",5555,FALSE);
	if (!ret)
	{
		::MessageBoxA(0,"error","err",3);
		return;
	}

	char* ss = "hello world.hello world.hello world.hello world.hello world.";
	ret = client_->Send((LPBYTE)ss,strlen(ss));
	if (!ret)
	{
		int i = ::GetLastError();
		::MessageBoxW(0,client_->GetLastErrorDesc(),L"err",3);
		return;
	}

	return;
}`

**Comment by ldcsaa** [comment]
1、OnHandShake后才能Send数据
2、对象的GetLastError()只对Start/Stop的的判断有效，其它情形下都用系统的 ::GetLastError()

**Comment by ugenehan** [comment]
> ::GetLastError()

是的，跟到源码里面是这样的。也就是要在OnHandShake判断后才能发送数据，
