### ISSUE TITLE
Pack方式可以传输大于0x3FFFFF的数据吗

### ISSUE THREAD

**Issue by hcaihao** [ldcsaa/HP-Socket#127]
以现在网速的条件来看，这个限制有点太小了，如何突破这个限制，需要修改哪些地方？或者有无提供分包发送的方法？还是要自己来实现？

XXXXXXXXXX YYYYYYYYYYYYYYYYYYYYYY

**Comment by ldcsaa** [comment]
不能，看文档。

**Comment by hcaihao** [comment]
可以通过修改源码实现吗，可否把这部分限制提升
