### ISSUE TITLE
vc2010  TestEcho-Http-4C工程报错   OP:4 Code:13 

### ISSUE THREAD

**Issue by hnsxcxwpf2** [ldcsaa/HP-Socket#128]
![image](https://user-images.githubusercontent.com/12248308/90125920-65712180-dd95-11ea-9215-b70d1e314e87.png)

Win10

**Comment by hnsxcxwpf2** [comment]
![1597315302(1)](https://user-images.githubusercontent.com/12248308/90125624-ea0f7000-dd94-11ea-9fa9-68c3f177c761.png)

**Comment by ldcsaa** [comment]
http 80
https 443

**Comment by hnsxcxwpf2** [comment]
这玩笑开大了
