### ISSUE TITLE
android studio 工程链接库，提示无法解决引用

### ISSUE THREAD

**Issue by jjqcat** [ldcsaa/HP-Socket#129]
HPSocket.h:296: error: undefined reference to HP_Destroy_TcpPullClient  HP_Create_TcpPullClient ，但so文件已经加入工程

**Comment by ldcsaa** [comment]
增加软连接 
libhpsocket.so.5

**Comment by jjqcat** [comment]
能截图说明下吗？在CMakeLists.txt文件里怎么增加软链接？谢谢

**Comment by jjqcat** [comment]
已经解决。现在有个疑问，模仿Windows下的demo：
class ClientComponent  : public CTcpPullClientListener
{
        ClientComponent  （）；
	virtual EnHandleResult OnConnect(ITcpClient* pSender, CONNID dwConnID);
	virtual EnHandleResult OnSend(ITcpClient* pSender, CONNID dwConnID, const BYTE* pData, int iLength);
	virtual EnHandleResult OnReceive(ITcpClient* pSender, CONNID dwConnID, int iLength);
	virtual EnHandleResult OnClose(ITcpClient* pSender, CONNID dwConnID, EnSocketOperation enOperation, int iErrorCode);

CTcpPullClientPtr m_Client;
}；
//cpp文件
ClientComponent  （）：m_Client（this)
{

}
Android上编译还是报上面的错

**Comment by jjqcat** [comment]
不好意思，前面的问题（undefined reference to HP_Destroy_TcpPullClient）还是未能解决。build.gradle也将so加入了dependencies

**Comment by ldcsaa** [comment]
HPSocket.cpp
这个文件要加入工程
