### ISSUE TITLE
vc2019编译出来的静态库 偶发性崩溃

### ISSUE THREAD

**Issue by hnsxcxwpf2** [ldcsaa/HP-Socket#130]
![1597470728(1)](https://user-images.githubusercontent.com/12248308/90306342-e39d0780-defe-11ea-9cd1-b0efccd0c6bf.png)
![1597470815(1)](https://user-images.githubusercontent.com/12248308/90306344-e4ce3480-defe-11ea-8158-a468ee410346.png)

**Comment by hnsxcxwpf2** [comment]
os是win10 x64

**Comment by ldcsaa** [comment]
不要一直创建 CTcpClient 对象。保存下来重复使用。

**Comment by hnsxcxwpf2** [comment]
我用完之后 用HP_Client_Stop 把它注销掉也不行?

**Comment by hnsxcxwpf2** [comment]
他这个错报的具体是什么错?

**Comment by ldcsaa** [comment]
自己检查代码
不要一直创建 CTcpClient 临时对象
