### ISSUE TITLE
CUdpClient  只能发出小于1432的数据包

### ISSUE THREAD

**Issue by boyucjz** [ldcsaa/HP-Socket#133]
使用SetMaxDatagramSize   设置为9000， 实际数据包大小为8000字节， 在接收端只能收到1432个字节，请问是不是还需要设置其它参数，谢谢。

**Comment by ldcsaa** [comment]
两端的 MaxDatagramSize 都不能小于数据包。

**Comment by boyucjz** [comment]
解决了，需要在启动之前设置  SetMaxDatagramSize
