### ISSUE TITLE
TcpClient 在一直有数据接收过程中调用 stop 方法关闭连接会阻塞

### ISSUE THREAD

**Issue by JarlenLai** [ldcsaa/HP-Socket#136]
我建立了一个TcpClient, 对端服务器会一直给我发数据, 在某个时刻我需要主动去停止TCP连接, 所以调用了TcpClient的stop方法,但是发现该方法阻塞了. 不知道有没有能强制关闭TCP连接的方法.

**Comment by ldcsaa** [comment]
看文档：不能在IO线程中调用Stop。
