### ISSUE TITLE
添加  Google 压缩算法 Brotl 的支持

### ISSUE THREAD

**Issue by btx638** [ldcsaa/HP-Socket#137]
请求添加  Google 压缩算法 Brotl 的支持， https://github.com/google/brotli

**Comment by ldcsaa** [comment]
不是同一类东西呀~

**Comment by btx638** [comment]
和 gzip 类似的网络数据压缩算法，请求添加以下类似的函数
SYS_GZipCompress
SYS_GZipUncompress

对应 Brotl 则是
SYS_BrotlCompress
SYS_BrotlUncompress

**Comment by ldcsaa** [comment]
以后会考虑加入
