### ISSUE TITLE
Error Code 對應清單

### ISSUE THREAD

**Issue by hugo4004** [ldcsaa/HP-Socket#139]
請問Error Code的對應清單在哪邊查的到? .NET版本的

**Comment by ldcsaa** [comment]
SYS_GetLastError : 对应windows/linux 系统错误码

HP_GetLastError : 只拥有 Start/Stop 操作，在 HPTypeDef.h 中定义

**Comment by Endt4sk** [comment]
In cmd console:
    net helpmsg Error_Code

**Comment by hugo4004** [comment]
HP-SOCKET.NET 5.7.2
Server > TcpServer-Adapter > PacketDataReceiveAdapter > sender.Send(id, data, data.Length) 
Client > TcpClient
在內網傳輸的時候會飄 2ms ~ 300ms 請問是哪邊的問題有沒有地方可以微調?
