### ISSUE TITLE
include中未包含全部头文件

### ISSUE THREAD

**Issue by zhaowq32** [ldcsaa/HP-Socket#141]
include未包含具体的Server/Client实现类头文件，是有其他方面考虑么？

**Comment by zhaowq32** [comment]
应该使用HPSocket.h中的导出函数来创建对象，而不是像demo中直接include对应实现类头文件。

**Comment by oPiZiL** [comment]
能够创建对象，但是有些没有src里面的头文件还是不能调用啊，比如   
`IUdpArqClient`
