### ISSUE TITLE
TCP客户端在服务端发送RST报文的时候，无法触发OnClose

### ISSUE THREAD

**Issue by oldxukaiming** [ldcsaa/HP-Socket#142]
![image](https://user-images.githubusercontent.com/16289214/96817579-2ffe4980-1452-11eb-8ec1-2dbe723f242a.png)
HP-SOCKET 客户端程序，在服务端给我发送RST包，无法触发OnClose
192.168.0.10为PC 客户端
192.168.0.121为服务端

**Comment by ldcsaa** [comment]
从未发现过这种情况，是不是你的通信线程被阻塞了。

**Comment by oldxukaiming** [comment]
通信线程阻塞?你是说接收线程吗?我的接收线程只是把收到的数据放入队列,没有做其他的事情,是不可能会堵塞的.其他服务器端发FIN包,会正常断开,也会触发OnClose事件
