### ISSUE TITLE
linux环境下，CUdpServer端程序关闭以后再次打开，无法接收原来运行CUdpClient端程序的数据

### ISSUE THREAD

**Issue by boyucjz** [ldcsaa/HP-Socket#143]
linux环境下，CUdpServer端程序关闭以后再次打开，无法接收原来运行CUdpClient端程序的数据，必须重启CUdpClient端程序，请问如何解决。
按我的理解CUdpServer关闭时，应该不通知CUdpClient端的程序，但是在linux下，CUdpClient端程序触发了onclose事件，心跳也关闭了。

**Comment by ldcsaa** [comment]
hp的udpserver/udpclient是基于连接的，可以用udpnode，udpnode不基于连接。

**Comment by boyucjz** [comment]
多谢，不过我用的是5.5.1版本，直接修改的testecho-udp源码， 请问能调整一些代码变为无连接的吗（修改5.5.1的代码）？

**Comment by ldcsaa** [comment]
可以在收到OnClose事件时执行重连逻辑，如何重连参考开发文档
