### ISSUE TITLE
大量小封包傳輸問題

### ISSUE THREAD

**Issue by hugo4004** [ldcsaa/HP-Socket#149]
請問我在使內網用的時候傳輸大量4k以下小封包傳輸時耗時飄的有點兇差不多的封包耗時會在 2ms ~ 300ms 上下浮動(10ms以內佔7成)，請問是哪邊的問題有沒有地方可以微調或建議? 感恩
HP-SOCKET.NET 5.7.2
Server > TcpServer-Adapter > PacketDataReceiveAdapter > sender.Send(id, data, data.Length)
Client > TcpClient

**Comment by ldcsaa** [comment]
1、Start 前设置参数 SendSendPolicy(SP_DIRECT)
2、OnPrepareConnect / OnPrepareListen 事件中设置 SYS_SSO_Nodelay(true)
