### ISSUE TITLE
UdpArqClient断开连接之后，server要过很久才能检测到断开连接

### ISSUE THREAD

**Issue by oPiZiL** [ldcsaa/HP-Socket#152]
使用`pSender->IsConnected(dwConnID)`判断client是否断开了连接

**Comment by mapleo** [comment]
HPSOCKET_API void __HP_CALL HP_TcpServer_SetKeepAliveTime(HP_TcpServer pServer, DWORD dwKeepAliveTime);
/* 设置异常心跳包间隔（毫秒，0 不发送心跳包，，默认：20 * 1000，如果超过若干次 [默认：WinXP 5 次, Win7 10 次] 检测不到心跳确认包则认为已断线） */
HPSOCKET_API void __HP_CALL HP_TcpServer_SetKeepAliveInterval(HP_TcpServer pServer, DWORD dwKeepAliveInterval);


注意下这两个API




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "oPiZiL"<notifications@github.com&gt;; 
发送时间: 2021年1月21日(星期四) 下午5:12
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [ldcsaa/HP-Socket] UdpArqClient断开连接之后，server要过很久才能检测到断开连接 (#152)





 
使用pSender-&gt;IsConnected(dwConnID)判断client是否断开了连接

**Comment by mapleo** [comment]
哦...UDP没用过



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "oPiZiL"<notifications@github.com&gt;; 
发送时间: 2021年1月21日(星期四) 下午5:12
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [ldcsaa/HP-Socket] UdpArqClient断开连接之后，server要过很久才能检测到断开连接 (#152)





 
使用pSender-&gt;IsConnected(dwConnID)判断client是否断开了连接

**Comment by mapleo** [comment]
/* 设置监测包尝试次数（0 则不发送监测跳包，如果超过最大尝试次数则认为已断线） */
HPSOCKET_API void __HP_CALL HP_UdpServer_SetDetectAttempts(HP_UdpServer pServer, DWORD dwDetectAttempts);
/* 设置监测包发送间隔（毫秒，0 不发送监测包） */
HPSOCKET_API void __HP_CALL HP_UdpServer_SetDetectInterval(HP_UdpServer pServer, DWORD dwDetectInterval);
/* 获取心跳检查次数 */
HPSOCKET_API DWORD __HP_CALL HP_UdpServer_GetDetectAttempts(HP_UdpServer pServer);
/* 获取心跳检查间隔 */
HPSOCKET_API DWORD __HP_CALL HP_UdpServer_GetDetectInterval(HP_UdpServer pServer);





类似TCP SERVER




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "oPiZiL"<notifications@github.com&gt;; 
发送时间: 2021年1月21日(星期四) 下午5:12
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [ldcsaa/HP-Socket] UdpArqClient断开连接之后，server要过很久才能检测到断开连接 (#152)





 
使用pSender-&gt;IsConnected(dwConnID)判断client是否断开了连接

**Comment by oPiZiL** [comment]
> /* 设置监测包尝试次数（0 则不发送监测跳包，如果超过最大尝试次数则认为已断线） */ HPSOCKET_API void __HP_CALL HP_UdpServer_SetDetectAttempts(HP_UdpServer pServer, DWORD dwDetectAttempts); /* 设置监测包发送间隔（毫秒，0 不发送监测包） */ HPSOCKET_API void __HP_CALL HP_UdpServer_SetDetectInterval(HP_UdpServer pServer, DWORD dwDetectInterval); /* 获取心跳检查次数 */ HPSOCKET_API DWORD __HP_CALL HP_UdpServer_GetDetectAttempts(HP_UdpServer pServer); /* 获取心跳检查间隔 */ HPSOCKET_API DWORD __HP_CALL HP_UdpServer_GetDetectInterval(HP_UdpServer pServer); 类似TCP SERVER
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "oPiZiL"<notifications@github.com&gt;; 发送时间: 2021年1月21日(星期四) 下午5:12 收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [ldcsaa/HP-Socket] UdpArqClient断开连接之后，server要过很久才能检测到断开连接 (#152) 使用pSender-&gt;IsConnected(dwConnID)判断client是否断开了连接 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我这么设置的  
```
    udp_server_->SetDetectAttempts(0);
    udp_server_->SetDetectInterval(0);
``` 
解决了
