### ISSUE TITLE
设置连接的附加数据

### ISSUE THREAD

**Issue by JunGenius** [ldcsaa/HP-Socket#154]
你好，作者。
我想请问下，如何实现客户端到服务端数据绑定 ？
比如客户端连接时，绑定一些附加数据 ,比如用户名，地址等信息 ， 那么服务端在OnAccept中如何能接受到客户端绑定的附加数据 ？类似  SetConnectionExtra  和 GetConnectionExtra ?
非常感谢.

**Comment by ldcsaa** [comment]
这些是应用层数据，通过应用层协议发送。
