### ISSUE TITLE
CheckConnection abort

### ISSUE THREAD

**Issue by oPiZiL** [ldcsaa/HP-Socket#155]
```
(#60953, 0x7F31C0A70700) > abort() [56] : Invalid request code
  => src/UdpClient.cpp (430) : BOOL CUdpClient::CheckConnection()
Aborted (core dumped)
```

**Comment by ldcsaa** [comment]
最简单解决方法： src/UdpClient.cpp (430)
return VERIFY(DetectConnection());
改为
return DetectConnection();

另外，请说说发生这种情况的场景。

**Comment by oPiZiL** [comment]
使用的是UdpArqServer/Client通讯，Server会周期性的给Client发送数据(5ms)，出现这个情况也是偶发，具体原因不详

**Comment by oPiZiL** [comment]
因为用的是Udp通讯，为了检测Client的意外退出，我在Server端调用了 `pSender->DisconnectSilenceConnections(500);
`， 如果这个被触发，是否可能导致client abort?

**Comment by ldcsaa** [comment]
下个版本修复。
