### ISSUE TITLE
建议 hp socket 在工作线程结束前触发一个回调函数

### ISSUE THREAD

**Issue by btx638** [ldcsaa/HP-Socket#157]
名称叫：
_HP_Set_FN_XXX_OnWorkerThreadStart
HP_Set_FN_XXX_OnWorkerThreadEnd_
参数1  pListener
参数2  用户自定义的回调函数

在每个工作线程的开始和结束，各调用一次
作用之一：给使用者在每个工作线程里初始化资源，和彻底清理资源的时机

**Comment by ldcsaa** [comment]
工作线程应该是对使用方透明的，初始化和清理可以在其它回调事件中执行。

**Comment by btx638** [comment]
初始化COM套间，释放COM套间等在一个工作线程的开始和结束必须执行一次， 否则没法使用 COM 相关的功能。
然而 hp socket 没有提供 OnWorkerThreadEnd 的事件，就没有释放 COM 套间的机会了

**Comment by btx638** [comment]
@ldcsaa 

> 工作线程应该是对使用方透明的，初始化和清理可以在其它回调事件中执行。

初始化COM套间，释放COM套间等在一个工作线程的开始和结束必须执行一次， 否则没法使用 COM 相关的功能。
然而 hp socket 没有提供 OnWorkerThreadEnd 的事件，就没有释放 COM 套间的机会了

**Comment by FunlyDay** [comment]
这是来自樊  邮箱的自动回复邮件。 您好，您发的邮件我已收到，我会及时查看并予以回复。
