### ISSUE TITLE
跨平台建议

### ISSUE THREAD

**Issue by rooong** [ldcsaa/HP-Socket#159]
HP-Socket整个核心库现在不同平台上有不同的代码管理：Linux的，Windows 的，Mac的，接入时，不同平台需要不同的代码库，管理起来非常不方便。

建议跨平台实现统一管理，这样在不同平台上都可以使用同一套代码，一方面减少通用代码维护多份，只需要根据不同平台做跨平台处理，维护起来更方便。

PS：不同平台的Demo倒是可以根据实现需求有不同的代码。

**Comment by ldcsaa** [comment]
不同平台只需引入库文件和相应include目录下的头文件即可。

**Comment by rooong** [comment]
> 不同平台只需引入库文件和相应include目录下的头文件即可。

这个是项目不想引入源代码管理的情况下用，如果想引入源代码的话，就会有我说的问题
