### ISSUE TITLE
hp-socket-5.8.2-bin-win 编译链接动态链接库没有问题，但是链接静态库出错

### ISSUE THREAD

**Issue by oPiZiL** [ldcsaa/HP-Socket#160]
error: LNK2019: unresolved external symbol __imp_HP_Create_UdpArqClient referenced in function

**Comment by ldcsaa** [comment]
（静态库引用方式参考： TestEcho-SSL-4C / TestEcho-SSL-PFM 示例 Demo）。
注意： 如果工程项目使用 HPSocket LIB 或 HPSocket4C LIB，需要在工程属性中定义预
处理宏 -> HPSOCKET_STATIC_LIB。
