### ISSUE TITLE
android ndk编译出错

### ISSUE THREAD

**Issue by huangran-qin** [ldcsaa/HP-Socket#161]
谢谢这个开源这个框架，我在window 10 ndk版本android-ndk-r14b环境下，调用下面命令
HP-Socket\Linux>build-android-ndk.bat APP_ABI=armeabi-v7a,x86

报错如下：
./project/android-ndk/jni/../../../src/common/../../include/hpsocket/GlobalErrno.h:29:10: fatal error: 'sysexits.h' file not found
#include <sysexits.h>

**Comment by ldcsaa** [comment]
用 android-ndk-r19 以上版本编译
