### ISSUE TITLE
HPSocketDLL动态库编译错误

### ISSUE THREAD

**Issue by ntuhubin** [ldcsaa/HP-Socket#162]
谢谢提供这么好用的通信框架，我在编译动态库时，遇到以下错误，不知道怎么解决。静态库可以编译成功。
机器环境：win7 64位，vs2017
1>mimalloc.lib(region.obj) : error LNK2001: 无法解析的外部符号 _mi_bitmap_try_find_claim_field
1>mimalloc.lib(region.obj) : error LNK2001: 无法解析的外部符号 mi_bitmap_unclaim
1>mimalloc.lib(region.obj) : error LNK2001: 无法解析的外部符号 _mi_bitmap_claim
1>mimalloc.lib(arena.obj) : error LNK2001: 无法解析的外部符号 _mi_bitmap_claim
1>mimalloc.lib(region.obj) : error LNK2001: 无法解析的外部符号 _mi_bitmap_is_claimed
1>mimalloc.lib(region.obj) : error LNK2001: 无法解析的外部符号 _mi_bitmap_is_any_claimed
1>mimalloc.lib(arena.obj) : error LNK2001: 无法解析的外部符号 _mi_bitmap_try_find_from_claim_across
1>mimalloc.lib(arena.obj) : error LNK2001: 无法解析的外部符号 _mi_bitmap_unclaim_across
1>mimalloc.lib(arena.obj) : error LNK2001: 无法解析的外部符号 _mi_bitmap_claim_across
1>mimalloc.lib(arena.obj) : error LNK2001: 无法解析的外部符号 _mi_bitmap_is_claimed_across

**Comment by ntuhubin** [comment]
动态库在debug下可以编译，realease版本下拿掉附加库mimalloc.lib也能编译通过，不知道拿掉这个mimalloc.lib是否有什么影响？

**Comment by ldcsaa** [comment]
mimalloc.lib 漏添加了一个 obj 文件，稍后修复。
