### ISSUE TITLE
TcpPullClientT 的Reset重写容易导致纯虚函数调用崩溃风险

### ISSUE THREAD

**Issue by starwang90** [ldcsaa/HP-Socket#163]
由于状态机异步原因，当服务器不存在的时候，用TcpPullClient因为析构函数中TcpClient的Stop函数调用了Reset接口是重载接口，在快速建立连接由快速delete类时候有崩溃风险提示pure virtual method called

**Comment by ldcsaa** [comment]
解决建议：
1、用 Agent 取代 Client。
2、Client 组件定义为属性，不要频繁创建/释放。

**Comment by ldcsaa** [comment]
升级到 5.8.5 版本应该能避免这个问题。
