### ISSUE TITLE
在CentOS7中OnClose事件和在Window系统中不一样

### ISSUE THREAD

**Issue by z514987467** [ldcsaa/HP-Socket#164]
开发框架：.NET CORE3.1
问题描述：
在Win10开发环境中，使用IClient连接服务失败会回调OnClose事件，但是在Docker下Centos7环境中不会回调

**Comment by int2e** [comment]
能否提供demo, 你是同步连接还是异步连接.

**Comment by ldcsaa** [comment]
hp-socket for .net 代码仓库：https://github.com/int2e/HPSocket.Net

**Comment by int2e** [comment]
请关闭问题, 问题已在 [HPSocket.Net/issues/14](https://github.com/int2e/HPSocket.Net/issues/14)处理
