### ISSUE TITLE
5.8.2  http SSL client / agent  连接  https://www.websocket.org/  无法到 onHandShake 就 close 了

### ISSUE THREAD

**Issue by btx638** [ldcsaa/HP-Socket#165]
环境：
系统：win 10
版本：5.8.2 
文件：HPSocket4C_U.dll x32
已经设置了 setupSSLContext(0)， 

经测试在同样的环境、设置、代码下，最后一个正常访问的版本是 5.6.4

**Comment by ldcsaa** [comment]
请参考 hp 发布包的自带demo

**Comment by btx638** [comment]
通过抓包发现是 TLS  版本的原因
5.6.4  TLSv1.2 
5.8.2  TLS v1
