### ISSUE TITLE
clang 崩溃

### ISSUE THREAD

**Issue by baidwwy** [ldcsaa/HP-Socket#166]
clang 5.0
ndk r16
hp 5.8.2
编译可以通过，但调用就崩溃，提示内存mi_xxx
切换回5.7.3 问题解决
怪兽大侠是否可以提供mimalloc，jemalloc选择

**Comment by yecate** [comment]
[https://github.com/microsoft/mimalloc/issues/381](url)

**Comment by baidwwy** [comment]
对就是这提示 SIGSEGV

**Comment by ldcsaa** [comment]
5.8.3 ndk 版将移除 mimalloc

**Comment by baidwwy** [comment]
@ldcsaa 经过测试 ，问题定位在5.8.2的修改
恢复这文件到5.8.1恢复正常了
https://github.com/ldcsaa/HP-Socket/blob/87492372875c160d2d39141b05ee6f28247fd697/Linux/include/hpsocket/SocketInterface.h#L37

**Comment by baidwwy** [comment]
而mimalloc，是在arm64崩，其它都正常

**Comment by ldcsaa** [comment]
> @ldcsaa 经过测试,关闭mimalloc后还是崩 ，问题定位在5.8.2的修改
> 恢复这文件到5.8.1恢复正常了
> https://github.com/ldcsaa/HP-Socket/blob/87492372875c160d2d39141b05ee6f28247fd697/Linux/include/hpsocket/SocketInterface.h#L37

你是 NDK - armv7 环境吗？

**Comment by baidwwy** [comment]
是

**Comment by ldcsaa** [comment]
@baidwwy 
改为
```
#if defined(__arm__)  && ！defined(__ANDROID__)
```
应该就可以了

**Comment by baidwwy** [comment]
> @baidwwy
> 改为
> 
> ```
> #if defined(__arm__)  && !defined(__ANDROID__)
> ```
> 
> 应该就可以了

5.8.3测试有效

**Comment by baidwwy** [comment]
arm64 也有效，结案

**Comment by ldcsaa** [comment]
@baidwwy 你用的是hp-socket哪些组件？

**Comment by baidwwy** [comment]
> @baidwwy 你用的是hp-socket哪些组件？

用的pack,
服务启动无反应，客户HasStarted,GetState等崩溃
received signal SIGSEGV, Segmentation fault.

因为我v7和v8来回切，没注意错误细节，导致我以为只是mimalloc问题

**Comment by ldcsaa** [comment]
@baidwwy 
可以试试这样定义：
```
#if defined(__arm__) && defined(__GNUC__) && !(defined(__clang__) || defined(__llvm__))
```

**Comment by baidwwy** [comment]
> @baidwwy
> 可以试试这样定义：
> 
> ```
> #if defined(__arm__) && defined(__GNUC__) && !(defined(__clang__) || defined(__llvm__))
> ```

有效
