### ISSUE TITLE
Example of code to be used on the client and server?

### ISSUE THREAD

**Issue by curiosport** [ldcsaa/HP-Socket#167]
I have seen your example that you put in the description but I am not sure which part goes on the client and which on the server, I would appreciate it if you could explain it to me.

**Comment by ldcsaa** [comment]
All demos are placed in the "demo/" folder. The demo project directory usually contains subdirectories such as "server/", "agent/" or "client/", which correspond to _server_, _agent_ or _client_ examples respectively.
