### ISSUE TITLE
关于Common\Thread.h中CThread::Start疑问

### ISSUE THREAD

**Issue by GTchenchao** [ldcsaa/HP-Socket#168]
在HPSOCKET 5.8.2.1版本的Thread.h一段关于智能指针的代码
`	BOOL Start(T* pRunner, F pFunc, P* pArg = nullptr, int iPriority = THREAD_PRIORITY_NORMAL, UINT uiStackSize = 0, LPSECURITY_ATTRIBUTES lpThreadAttributes = nullptr)
	{
		BOOL isOK = TRUE;

		if(!IsRunning())
		{
			Release();

			unique_ptr<TWorker> wkPtr(TWorker::Construct(pRunner, pFunc, pArg));
			wkPtr->CopyTo(m_Worker);

			if(iPriority == THREAD_PRIORITY_NORMAL)
				m_hThread = (HANDLE)_beginthreadex(lpThreadAttributes, uiStackSize, ThreadProc, (LPVOID)wkPtr.get(), 0, &m_uiThreadID);
			else
			{
				m_hThread = (HANDLE)_beginthreadex(lpThreadAttributes, uiStackSize, ThreadProc, (LPVOID)wkPtr.get(), CREATE_SUSPENDED, &m_uiThreadID);

				if(IsValid())
				{
					::SetThreadPriority(m_hThread, iPriority);
					::ResumeThread(m_hThread);
				}
			}

			if(IsValid())
				wkPtr.release();
			else
			{
				::SetLastError(ERROR_CREATE_FAILED);
				isOK = FALSE;
			}
		}
		else
		{
			::SetLastError(ERROR_INVALID_STATE);
			isOK = FALSE;
		}

		return isOK;
	}`
其中wkPtr.release()是释放指针的占有权，但是这意味着TWorker::Construct中New的指针变成野指针了？参考如下代码
`#include <iostream>
#include <memory>

int main() {

        std::unique_ptr<int> uptr(new int(10));  //绑定动态对象
        //std::unique_ptr<int> uptr2 = uptr;  //不能賦值
        //std::unique_ptr<int> uptr2(uptr);  //不能拷内
        std::unique_ptr<int> uptr2 = std::move(uptr); //轉換所有權

        if(uptr == nullptr)
            printf("uptr give up *int\n");

        int * p = uptr2.release(); //uptr2释放对指针的控制权，返回指针，并将uptr2置为空

        if(uptr2 == nullptr)
          printf("uptr2 give up *int\n");

        printf("%d\n", *p);
        delete p;

        return 0;
}`
希望能够能得到大神的解答，谢谢！

**Comment by ldcsaa** [comment]
TWorker::Construct中New的指针要作为线程入库参数传递到工作线程中的呀！！

**Comment by GTchenchao** [comment]
哦，是的。脑袋没转过弯
