### ISSUE TITLE
请问哪些参数配置可以减少UDP丢包

### ISSUE THREAD

**Issue by boyucjz** [ldcsaa/HP-Socket#169]
用的是HP-Socket-master 5.5.3   使用UdpServer接收UDP数据，  数据包长度为88字节，  但是数据包比较多，每秒8000多个数据包；   发现丢包严重， 有什么参数配置可以减少丢包吗；  软件运行在centos 7下，已经针对操作系统网络参数进行的调整（增加接收缓冲区大小），  不过还是发现如果同时到达的数据包较多时，丢包严重。 短时间运行不丢包，但是连续运行时会丢包（好像是处理不过来），  有没有什么参数可以增加  UdpServer  接收缓冲区？    谢谢！

**Comment by ldcsaa** [comment]
1、新版本作了性能优化，升级到新版本(5.8.3)可以减少丢包几率。
2、把OnReceive事件中处理的业务逻辑转移到独立线程池，OnReceive尽快返回。能大大提升数据接收能力。

另外，如果服务端和客户端都用hp-socket的话，可以改用 ARQ UDP Server/Client，能确保不丢包。

**Comment by boyucjz** [comment]
谢谢
