### ISSUE TITLE
5.8.3使用静态库Release模式下 出现链接错误，跟mimalloc相关

### ISSUE THREAD

**Issue by zhaokaixs** [ldcsaa/HP-Socket#170]
1>libucrt.lib(align.obj) : error LNK2005: _aligned_malloc 已经在 HPSocket.lib(mi_alloc.obj) 中定义

**Comment by ldcsaa** [comment]
你先改用 jemalloc 吧~

**Comment by zhaokaixs** [comment]
收到，谢谢



---原始邮件---
发件人: "Bruce ***@***.***&gt;
发送时间: 2021年6月8日(周二) 晚上8:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ldcsaa/HP-Socket] 5.8.3使用静态库Release模式下 出现链接错误，跟mimalloc相关 (#170)




 
你先改用 jemalloc 吧~

**Comment by zhaokaixs** [comment]
还有一个问题就是release模式下，使用静态库的方式（/MT） 出现double free的指针崩溃问题， 而且找不到规律, 看了下堆栈都是释放的对象已经是null 导致的，现在把hp的静态库 链接的jemalloc去掉 就不崩溃了，是不是静态库用jemalloc不太合适，换成dll就好了

**Comment by ldcsaa** [comment]
链接程序时试试把 hpsocket lib 放在最右边。

**Comment by zhaokaixs** [comment]
好的，我试试，我是把hp lib工程放到了解决方案里，然后右键在我的项目里，点引用 选择了hp，&nbsp; 我觉得使用lib的方式，应该是把jemalloc也加载到我本身的进程了



---原始邮件---
发件人: "Bruce ***@***.***&gt;
发送时间: 2021年6月23日(周三) 下午5:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ldcsaa/HP-Socket] 5.8.3使用静态库Release模式下 出现链接错误，跟mimalloc相关 (#170)




 
链接程序时试试把 hpsocket lib 放在最右边。

**Comment by ldcsaa** [comment]
> 1>libucrt.lib(align.obj) : error LNK2005: _aligned_malloc 已经在 HPSocket.lib(mi_alloc.obj) 中定义

试试 5.8.4，应该解决了这个问题。
