### ISSUE TITLE
VS2013

### ISSUE THREAD

**Issue by yyfyan** [ldcsaa/HP-Socket#171]
你好，编译库时，能用vs2013吗，我看工程里只有2010,2015,2017和2019。

**Comment by ldcsaa** [comment]
没有2013

**Comment by yyfyan** [comment]
下载的bin文件夹里面的lib和DLL，可以在VS2013中使用吗。

**Comment by yyfyan** [comment]
下载的bin文件夹里面的lib和DLL，可以在VS2013中使用吗。 @ldcsaa

**Comment by ldcsaa** [comment]
dll应该可以。
