### ISSUE TITLE
关于send函数

### ISSUE THREAD

**Issue by zhscnd** [ldcsaa/HP-Socket#172]
现在的send函数如果发现缓存不够，就会去分配内存，但是这个时候如果分配内存失败，就会抛出异常，进而使程序飞掉。能否在分配内存失败时不抛出异常，只是send函数返回失败，这样程序就不会飞掉了，send失败的数据后续再继续调用send函数就可以了。

**Comment by ldcsaa** [comment]
不单是send，任何一个操作或函数调用都可能分配内存。很难对所有方法都进行检查和处理。
因此，最现实的方法是监控主机或应用的内存使用率，接入报警。
对于send操作，检查pending data length，进行限流发送。

**Comment by zhscnd** [comment]
@ldcsaa 好的，另外再问一个问题，可以在OnReceive回调中调用PauseReceive函数吗

**Comment by ldcsaa** [comment]
可以

**Comment by zhscnd** [comment]
@ldcsaa 你好，我现在使用TcpPackServer和TcpPackClient来传文件，server在Ubuntu上，client在windows上。从client传输文件到server，server端在写文件速度比较慢的时候会调用PauseReceive，client端在发送的时候也有检查pending data length，进行限流发送。现在经过测试，有的时候会出现传输后文件大小不一致的情况，也有出现文件大小一致，但是MD5比对不一致的情况。此问题遇到一段时间了，我也在看我的代码有没有问题，目前没有发现代码有什么问题，但是就出现了刚才说的情况。我现在准备测试不调用PauseReceive，看有没有问题。

**Comment by ldcsaa** [comment]
你先排查自己的业务处理逻辑代码。

**Comment by zhscnd** [comment]
@ldcsaa 应该和我的业务代码没有关系，业务代码很简单，我也喊其他人帮忙看过了，我具体给你说说。
下面的代码为代码1：
			PacketInfo* pPacket;
			while (true)
			{
				if (m_aIdlePackets.isEmpty() == false)//表示还有空闲的缓存
				{
					pthread_mutex_lock(&m_idlePacketsMutex);
					pPacket = m_aIdlePackets.takeFirst();
					pthread_mutex_unlock(&m_idlePacketsMutex);

					memcpy(pPacket->pData, pData, iLength);
					pPacket->nUsedLen = iLength;

					pthread_mutex_lock(&m_dataPacketsMutex);
					m_aDataPackets.push_back(pPacket);
					pthread_mutex_unlock(&m_dataPacketsMutex);

					break;
				}
				else
				{
					pthread_mutex_lock(&m_pauseReceiveMutex);
					if (m_bPauseReceive == false)
					{
						m_pSocket->PauseReceive(m_dwConnID, TRUE);//在另外的处理数据的线程会调用恢复接收
						m_bPauseReceive = true;
					}
					pthread_mutex_unlock(&m_pauseReceiveMutex);

					usleep(1000);
				}
			}
下面的代码为代码2：			
			PacketInfo* pPacket;
			while (true)
			{
				if (m_aIdlePackets.isEmpty() == false)//表示还有空闲的缓存
				{
					pthread_mutex_lock(&m_idlePacketsMutex);
					pPacket = m_aIdlePackets.takeFirst();
					pthread_mutex_unlock(&m_idlePacketsMutex);

					memcpy(pPacket->pData, pData, iLength);
					pPacket->nUsedLen = iLength;

					pthread_mutex_lock(&m_dataPacketsMutex);
					m_aDataPackets.push_back(pPacket);
					pthread_mutex_unlock(&m_dataPacketsMutex);

					break;
				}
				else
				{
					//如果没有空间，直接临时分配
					pPacket = new PacketInfo;
					pPacket->pData = new BYTE[MAX_PACKET_SIZE];
					memcpy(pPacket->pData, pData, iLength);
					pPacket->nUsedLen = iLength;

					pthread_mutex_lock(&m_dataPacketsMutex);
					m_aDataPackets.push_back(pPacket);
					pthread_mutex_unlock(&m_dataPacketsMutex);
					break;
				}
			}
下面的代码为代码3：
			PacketInfo* pPacket;
			while (true)
			{
				if (m_aIdlePackets.isEmpty() == false)
				{
					pthread_mutex_lock(&m_idlePacketsMutex);
					pPacket = m_aIdlePackets.takeFirst();
					pthread_mutex_unlock(&m_idlePacketsMutex);

					memcpy(pPacket->pData, pData, iLength);
					pPacket->nUsedLen = iLength;

					pthread_mutex_lock(&m_dataPacketsMutex);
					m_aDataPackets.push_back(pPacket);
					pthread_mutex_unlock(&m_dataPacketsMutex);

					break;
				}
				else
				{
					usleep(1000);//处理数据的线程会一直处理数据，处理完成一个数据后就会将缓存释放到m_aIdlePackets中
				}
			}
上面的代码就是OnReceive中的代码片段，每次测试的时候，除了上面的代码有区别，其他地方的代码完全一致，在测试中代码1和代码3均会有之前我说的问题，代码2测试则正常。所以我感觉很奇怪

**Comment by zhscnd** [comment]
后面通过测试发现，代码都没有问题，原来是由于系统太繁忙了，硬盘负荷太高引起的，换了个机器测试就对了。写文件函数的返回值和返回的写入数量都有检查，都是正常的，但是就是最后生成的文件有时会不对，搞不懂了。

**Comment by ldcsaa** [comment]
会不会是写文件顺序有问题或者出现竞争条件。

**Comment by zhscnd** [comment]
换了几台机器测试，目前就发现一台机器有问题，只要在那台机器上作为目标写文件，肯定会有问题，只是看出现得早或者晚。写文件的顺序我们已经检查了很多次，应该是没有问题的，就只有一个线程写文件。你说的出现竞争是指多个线程去写这个文件吗？我现在只有一个线程写。
