### ISSUE TITLE
TcpPullAgent对象调用GetConnectionState()方法时有可能返回6422588

### ISSUE THREAD

**Issue by yj-zhang** [ldcsaa/HP-Socket#173]
您好，
       我这面用的是5.8.2版本的库。今天调试程序发现获取某个连接的状态出现错误，GetConnectionState()方法返回了不在TcpConnectionState枚举范围内的值：6422588
`_agent.GetConnectionState(connId);`
       请问这是为什么，这说明出了什么问题吗？是否我使用错误，谢谢!

**Comment by ldcsaa** [comment]
C++没有这个方法，你用什么语言？

**Comment by yj-zhang** [comment]
很高兴收到您的回复！         我用的语言是c#，是用的这个库的.Net版本。         我是想通过调用GetConnectionState这个方法来获取指定连接的状态。谢谢！-------- 原始邮件 --------发件人： Bruce Liang ***@***.***>日期： 2021年6月25日周五 晚上9:51收件人： ldcsaa/HP-Socket ***@***.***>抄送： yj-zhang ***@***.***>, Author ***@***.***>主    题： Re: [ldcsaa/HP-Socket] TcpPullAgent对象调用GetConnectionState()方法时有可能返回6422588 (#173)

C++没有这个方法，你用什么语言？

**Comment by yj-zhang** [comment]
请问C++版本的库 使用TcpPullAgent如何获取每一个连接的当前状态？
我使用的.Net版本库地址如下：
[int2e/HPSocket.Net：](https://github.com/int2e/HPSocket.Net)
里面的TcpPullAgent组件有一个GetConnectionState()方法。

**Comment by ldcsaa** [comment]
IsConnected(CONNID dwConnID)

**Comment by yj-zhang** [comment]
非常感谢您的回复！-------- 原始邮件 --------发件人： Bruce Liang ***@***.***>日期： 2021年6月29日周二 晚上8:38收件人： ldcsaa/HP-Socket ***@***.***>抄送： yj-zhang ***@***.***>, Author ***@***.***>主    题： Re: [ldcsaa/HP-Socket] TcpPullAgent对象调用GetConnectionState()方法时有可能返回6422588 (#173)
IsConnected(CONNID dwConnID)
