### ISSUE TITLE
UDPClint 和 UDPNode 两者模式对比

### ISSUE THREAD

**Issue by yyfyan** [ldcsaa/HP-Socket#176]
UDPClint 和 UDPNode 两者除了基于连接和不基于连接外，还有什么区别。

**Comment by yyfyan** [comment]
若有两个UDPNode同时向某个UDPNode发数据，UDPNode的Onrecevie行为是什么样的，两个发过来的数据是同时过来Onrecevie的，还是分时直接用地址/端口区分就行？ @ldcsaa

**Comment by ldcsaa** [comment]
OnReceive 的顺序不确定，根据你自己的场景用 IP/PORT 标识或应用层数据做标识。

**Comment by yyfyan** [comment]
这个UDPNode的OnReceive 是线程不安全的吗？

**Comment by ldcsaa** [comment]
UDPNode OnReceive 可能会同时收到相同地址的多个包

**Comment by yyfyan** [comment]
UDPNode 跟Winsock一样？
