### ISSUE TITLE
功能建议，实现 http nat 长连接通道 

### ISSUE THREAD

**Issue by 156704883** [ldcsaa/HP-Socket#177]
实现类似  netty 框架 中的  http 长连接通道
tcp http client--------keep-alive ------> tcp http server
对于 http client 发起连接方，可以发送 request  接收 response , 也可以接收 request   发送 response 
对于 http server 接收放，      可以接收 request   发送 response，也可以发送 request  接收 response 
 
![image](https://user-images.githubusercontent.com/49087478/124533475-f38a4680-de44-11eb-91d7-dd749417a71c.png)

**Comment by ldcsaa** [comment]
双向发送，建议考虑一下HTTP2

**Comment by 156704883** [comment]
> 双向发送，建议考虑一下HTTP2

嗯，看到宇视的门禁开发协议中有支持这种双向发送的，然后看了一下他们的 java demo ,发现双向发送的功能，这样实现了内网的设备可以很方便的穿透到外网，外网通过这个链接直接用 http Request 就可以请求到设备了

**Comment by ldcsaa** [comment]
最简单就是用websocket实现双向发送。
