### ISSUE TITLE
Qt Mingw编译链Tcp Server使用异常

### ISSUE THREAD

**Issue by 84506232** [ldcsaa/HP-Socket#180]
Windows，QT5.12.9 MinGW 32bit，非unicode版本。
调用CTcpServerListener:start方法，程序奔溃；
使用MSVC2017编译链一切正常，请问是什么原因？
刚看到一篇文章：https://blog.csdn.net/a13576560181/article/details/106378021
不知道Mingw是否支持调用C++动态库，奇怪的是UDP一切正常。

**Comment by yecate** [comment]
mingw调用 msvc 的4c接口是没有问题的,如果是c++就别想了, 你发的博客里面也是在mingw里面包装了一层4c接口

**Comment by 84506232** [comment]
好的，谢谢！
