### ISSUE TITLE
ubuntu系统中调用CTcpPackServerPtr的Stop函数时程序就卡住了

### ISSUE THREAD

**Issue by songxue3073** [ldcsaa/HP-Socket#182]
ubuntu系统在QT中使用HP-Socket时调用CTcpPackServerPtr的Stop函数时程序就一直阻塞卡住了，请问这个问题如何处理？

**Comment by ldcsaa** [comment]
不能在OnReceive、OnSend、OnClose 等通讯事件中调用Stop
