### ISSUE TITLE
在动态库中引入hpsocket库的错误

### ISSUE THREAD

**Issue by fordata47** [ldcsaa/HP-Socket#193]
Linux平台下，centos7系统，在一个so动态库工程中静态方式引入hpsocket库，仅使用tcp协议原生socket通信一切正常，但使用http协议后会出现onReceive事件buffer数据溢出VS2019远程调试崩溃。如果调用so文件的工程也同样静态引入hpsocket库才能解决此问题

**Comment by ldcsaa** [comment]
1、首先排除内存分配器的影响，去掉mimalloc/jemalloc，使用系统malloc重新编译试试
2、如果有条件的话，开启core dump，用gdb分析崩溃的core dump文件
3、如果问题还没能解决，可以制作一个简单的实例demo上传上来，我帮你看看（注意：示例要包含源代码和编译脚本）
