### ISSUE TITLE
端口不一致

### ISSUE THREAD

**Issue by scorpiostudio** [ldcsaa/HP-Socket#194]
客户端使用HP_Client_GetLocalAddress获取的端口和服务端使用HP_Server_GetRemoteAddress获取客户端端口在少数情况下会不一致的问题

**Comment by ldcsaa** [comment]
广域网环境下，路由器会对内外网IP端口做NAT装换的呀！
例如 192.168.1.100:5000 --NAT--> 210.34.68.192:6000，
客户端取到的是 5000，服务端取到的是6000。
