### ISSUE TITLE
使用hpsocket静态库启用ssl，同时依赖webrtc静态库，报如下的很多错误，请问有什么解决办法吗？

### ISSUE THREAD

**Issue by SlimSnow** [ldcsaa/HP-Socket#196]
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_assign 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_bits 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_cmp 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_cmp_parameters 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_copy_parameters 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_free 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_get0_DH 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_get0_DSA 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_get0_EC_KEY 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_get0_RSA 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_get1_DH 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_get1_DSA 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_get1_EC_KEY 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_get1_RSA 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_id 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_missing_parameters 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_new 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_set1_DSA 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_set1_EC_KEY 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_set1_RSA 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_set_type 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_size 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_type 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(evp.obj) : error LNK2005: EVP_PKEY_up_ref 已经在 HPSocket_UD.lib(p_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_callback_ctrl 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_clear_flags 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_copy_next_retry 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_ctrl 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_ctrl_pending 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_find_type 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_free 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_free_all 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_get_data 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_get_init 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_get_new_index 已经在 HPSocket_UD.lib(bio_meth.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_get_retry_reason 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_get_shutdown 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_gets 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_indent 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_int_ctrl 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_meth_free 已经在 HPSocket_UD.lib(bio_meth.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_meth_new 已经在 HPSocket_UD.lib(bio_meth.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_meth_set_create 已经在 HPSocket_UD.lib(bio_meth.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_meth_set_ctrl 已经在 HPSocket_UD.lib(bio_meth.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_meth_set_destroy 已经在 HPSocket_UD.lib(bio_meth.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_meth_set_gets 已经在 HPSocket_UD.lib(bio_meth.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_meth_set_puts 已经在 HPSocket_UD.lib(bio_meth.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_meth_set_read 已经在 HPSocket_UD.lib(bio_meth.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_meth_set_write 已经在 HPSocket_UD.lib(bio_meth.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_method_type 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_new 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_next 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_number_read 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_number_written 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_pop 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_ptr_ctrl 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_push 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_puts 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_read 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_set_data 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_set_flags 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_set_init 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_set_shutdown 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_test_flags 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_up_ref 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_vfree 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: BIO_write 已经在 HPSocket_UD.lib(bio_lib.obj) 中定义
4>webrtc.lib(bio.obj) : error LNK2005: ERR_print_errors 已经在 HPSocket_UD.lib(err_prn.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: ERR_load_SSL_strings 已经在 HPSocket_UD.lib(ssl_err.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: OPENSSL_init_ssl 已经在 HPSocket_UD.lib(ssl_init.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_check_private_key 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_clear_options 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_free 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_get0_privatekey 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_get_ciphers 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_get_ex_data 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_get_keylog_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_get_options 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_get_quiet_shutdown 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_new 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_alpn_protos 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_alpn_select_cb 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_cipher_list 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_ex_data 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_keylog_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_msg_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_next_proto_select_cb 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_next_protos_advertised_cb 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_options 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_psk_client_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_psk_server_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_quiet_shutdown 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_session_id_context 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_set_tmp_dh_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_up_ref 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_CTX_use_psk_identity_hint 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_accept 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_certs_clear 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_check_private_key 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_clear 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_clear_options 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_connect 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_do_handshake 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_free 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get0_alpn_selected 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get0_next_proto_negotiated 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_SSL_CTX 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_cipher_list 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_ciphers 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_client_random 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_current_cipher 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_current_compression 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_current_expansion 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_default_timeout 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_error 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_ex_data 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_fd 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_finished 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_info_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_options 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_peer_finished 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_pending_cipher 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_privatekey 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_psk_identity 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_psk_identity_hint 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_quiet_shutdown 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_rbio 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_read_ahead 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_rfd 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_server_random 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_servername 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_servername_type 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_shared_ciphers 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_shutdown 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_verify_mode 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_wbio 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_get_wfd 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_in_init 已经在 HPSocket_UD.lib(statem.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_is_dtls 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_is_init_finished 已经在 HPSocket_UD.lib(statem.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_is_server 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_new 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_peek 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_pending 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_read 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_renegotiate 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_renegotiate_pending 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_select_next_proto 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_session_reused 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set0_rbio 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set0_wbio 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_SSL_CTX 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_accept_state 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_alpn_protos 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_bio 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_cipher_list 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_connect_state 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_ex_data 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_fd 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_info_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_msg_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_options 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_psk_client_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_psk_server_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_quiet_shutdown 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_read_ahead 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_rfd 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_session_id_context 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_shutdown 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_tmp_dh_callback 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_set_wfd 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_shutdown 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_use_psk_identity_hint 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_want 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义
4>webrtc.lib(ssl_lib.obj) : error LNK2005: SSL_write 已经在 HPSocket_UD.lib(ssl_lib.obj) 中定义

**Comment by ldcsaa** [comment]
两个库都打包了 opessl，取消其中一个库的打包即可。
