### ISSUE TITLE
VS2019编译Release版本，选择/MD时出现mi_alloc.obj重定义问题

### ISSUE THREAD

**Issue by HeyFox** [ldcsaa/HP-Socket#198]
错误	LNK2005	_calloc 已经在 HPSocket.lib(mi_alloc.obj) 中定义	ConsoleApplication1	C:\Users\pipiya\Desktop\CODE\H_Fox\远程\ConsoleApplication1\ConsoleApplication1\ucrt.lib(api-ms-win-crt-heap-l1-1-0.dll)	1	

错误	LNK2005	_free 已经在 HPSocket.lib(mi_alloc.obj) 中定义	ConsoleApplication1	C:\Users\pipiya\Desktop\CODE\H_Fox\远程\ConsoleApplication1\ConsoleApplication1\ucrt.lib(api-ms-win-crt-heap-l1-1-0.dll)	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2005	_malloc 已经在 HPSocket.lib(mi_alloc.obj) 中定义	ConsoleApplication1	C:\Users\pipiya\Desktop\CODE\H_Fox\远程\ConsoleApplication1\ConsoleApplication1\ucrt.lib(api-ms-win-crt-heap-l1-1-0.dll)	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2005	_realloc 已经在 HPSocket.lib(mi_alloc.obj) 中定义	ConsoleApplication1	C:\Users\pipiya\Desktop\CODE\H_Fox\远程\ConsoleApplication1\ConsoleApplication1\ucrt.lib(api-ms-win-crt-heap-l1-1-0.dll)	1

**Comment by ldcsaa** [comment]
试试最新版
