### ISSUE TITLE
HpSocket参考例子实现了websocket server，在关闭客户端连接的时候，如何能让浏览器客户端收到Close code

### ISSUE THREAD

**Issue by zhaokaixs** [ldcsaa/HP-Socket#204]
是否要server断先发送一个控制码，再close连接比较好呢

**Comment by ldcsaa** [comment]
先发送控制码，然后 调用 Release(connid)关闭连接。

**Comment by zhaokaixs** [comment]
> 

浏览器 这个 websocket.close([code[, reason]]) ,code[int]和reason[字符串],   使用HPSocket 调用SendWSMessage 发送呗？

**Comment by zhaokaixs** [comment]
`
			BOOL bFinal = TRUE;
			BYTE iReserved = 0x00, iOperationCode = 0x08;
			std::string a;
			uint16_t code = htons(1013);
			a.append((char*)&code, 2);
			a.append("fuck");
			pSender->SendWSMessage(nf->_connid, bFinal, iReserved, iOperationCode, (BYTE*)a.c_str(), (int)a.size());
			pSender->Release(nf->_connid);
`
实现了

**Comment by ldcsaa** [comment]
U R welcom ~
