### ISSUE TITLE
建议 hp socket 在每个工作线程的开始和结束各触发一个回调函数

### ISSUE THREAD

**Issue by btx638** [ldcsaa/HP-Socket#205]
名称叫：
HP_Set_FN_XXX_OnWorkerThreadStart
HP_Set_FN_XXX_OnWorkerThreadEnd
参数1 pListener
参数2 用户自定义的回调函数

在每个工作线程的开始和结束，各调用一次
作用之一：给使用者在每个工作线程里初始化资源，和彻底清理资源的时机

其中应用一个场景如下：
初始化COM套间，释放COM套间等在一个工作线程的开始和结束必须执行一次， 否则没法使用 COM 相关的功能。

**Comment by ldcsaa** [comment]
1、目前没有计划在Socket工作线程的创建/结束中提供回调操作。
2、HPSocket的线程池组件IHPThreadPool提供了工作线程创建/结束回调事件。你可以把业务逻辑放到HP线程池组件中处理。
