### ISSUE TITLE
错误的收到OnConnect通知

### ISSUE THREAD

**Issue by woowloop** [ldcsaa/HP-Socket#206]
5.8.5版 在服务器关闭连接端口的情况下 不停的尝试连接会小概率的收到EnHandleResult OnConnect(CONNID dwConnID)通知 更严重的是这时候如果在send数据 会触发EnHandleResult OnReceive(CONNID dwConnID, const BYTE* pData, int iLength)且收到的内容为发送的内容。。。。

**Comment by ldcsaa** [comment]
有可能是其他程序意外绑定了服务器端口。
如：服务器端口在随机分配端口范围内。

**Comment by introspection3** [comment]
sir,you should add lib to conan & vcpkg
