### ISSUE TITLE
改造了里面ssl部分，使用动态加载so的方式，同时加载了openssl库和gmssl问题

### ISSUE THREAD

**Issue by zhangleia** [ldcsaa/HP-Socket#207]
我改造了里面ssl部分，使用动态加载so的方式，同时加载了openssl库和gmssl，但是在调用的时候遇到一些问题，会偶发崩溃的问题，系统有高手可以交流指点下。QQ 845197436

**Comment by ldcsaa** [comment]
自己研究吧
