### ISSUE TITLE
C# OnAccept()事件参数pClient代表什么？

### ISSUE THREAD

**Issue by Viki8507** [ldcsaa/HP-Socket#21]
OnAccept事件委托定义了两个参数：
public delegate HandleResult OnAcceptEventHandler(IntPtr connId, IntPtr pClient);
想问问第二个参数pClient的含义？
看了C++版本代码，回调出来的就是一个原始SOCKET，C#没有源码，所以不清楚具体含义。

**Comment by ldcsaa** [comment]
source code dir: HP-Socket\Demo\Other Languages Demos\C#\HPSocketCS\HPSocketCS
