### ISSUE TITLE
vs2022 not supported

### ISSUE THREAD

**Issue by netyang789** [ldcsaa/HP-Socket#210]

**Comment by baidwwy** [comment]
+1

**Comment by ldcsaa** [comment]
vs2022 will be supported in nest version.
Yet, you can do it yourself manually:

1. copy Dependent/*/142 to Dependent/*/143
2. copy Project/HPSocket*-2019 to Project/HPSocket*-2022
3. copy Project/HPSocket-2019.sln to Project/HPSocket-2022.sln
4. edit Project/HPSocket-2022.sln, modify the '.vcxproj' paths

**Comment by ldcsaa** [comment]
Next version would be supported.

**Comment by ldcsaa** [comment]
5.8.7
