### ISSUE TITLE
suggestion: add doc about how to build (config)

### ISSUE THREAD

**Issue by introspection3** [ldcsaa/HP-Socket#213]
suggestion: add doc about how to build (config)

**Comment by introspection3** [comment]
we can't build after git clone directly

**Comment by introspection3** [comment]
@ldcsaa no,we use vs2022,but many files can't be found.

**Comment by introspection3** [comment]
oh,no,you use mfc??????

**Comment by introspection3** [comment]
#include "afxres.h"

**Comment by ldcsaa** [comment]
NOT MFC, but ATL.

**Comment by ldcsaa** [comment]
> @ldcsaa no,we use vs2022,but many files can't be found.

sea #210

**Comment by ldcsaa** [comment]
Next version would be supported.

**Comment by FunlyDay** [comment]
这是来自樊  邮箱的自动回复邮件。 您好，您发的邮件我已收到，我会及时查看并予以回复。
