### ISSUE TITLE
return a pointer is too dangerous

### ISSUE THREAD

**Issue by introspection3** [ldcsaa/HP-Socket#214]
TSocketObj* CTcpAgent::FindSocketObj(CONNID dwConnID)
{
	TSocketObj* pSocketObj = nullptr;

	if(m_bfActiveSockets.Get(dwConnID, &pSocketObj) != TSocketObjPtrPool::GR_VALID)
		pSocketObj = nullptr;

	return pSocketObj;
}

**Comment by ldcsaa** [comment]
rest assured
