### ISSUE TITLE
posgresssql的libpq与HpSocket的libhpsocket无法共存

### ISSUE THREAD

**Issue by s8642795130** [ldcsaa/HP-Socket#215]
在centos7下使用posgress数据库，一切正常。
仅仅是引用了libhpsocket库之后，程序如果执行到了libpq(posgresssql的一个库文件)下的所有函数均会直接崩溃，提示段错误，无法返回报错信息。
VS2019远程开发，当前版本HPSocket 5.8.3，替换最新版(5.8.7)的lib问题依旧

**Comment by ldcsaa** [comment]
试试以下方法：
方法一：使用HPSocket动态库
方法二：排除 mimalloc或ssl重新编译HPSocket库文件
    _**./compile.sh -m system -s false**_

**Comment by s8642795130** [comment]
去掉ssh和mimalloc后可以与libpq共存了.
我得编译命令为:
./compile.sh -m system -s false -d false -u false

**Comment by ldcsaa** [comment]
> 去掉ssh和mimalloc后可以与libpq共存了.
> 我得编译命令为:
> ./compile.sh -m system -s false -d false -u false

去掉其中之一试试是哪个库造成的问题。
