### ISSUE TITLE
httpserver，通过GetUrlField函数取HUF_SCHEMA的值为什么是空的呢？

### ISSUE THREAD

**Issue by bybaby** [ldcsaa/HP-Socket#216]
sprintf_s(pContext->req.scheme, sizeof(pContext->req.scheme), _T("%s"), pSender->GetUrlField(dwConnID, HUF_SCHEMA));
HUF_HOST也是空的
LPCSTR lpszEncoding = pSender->GetTransferEncoding(dwConnID);
LPCSTR lpszContentType = pSender->GetContentType(dwConnID);
这几个也是空的，是我方法不对吗？

**Comment by ldcsaa** [comment]
没有传递过来当然为空了。

**Comment by bybaby** [comment]
别的先不说，HUF_SCHEMA、HUF_HOST不是必须有的吗？
![image](https://user-images.githubusercontent.com/19551401/162852499-ee73cd31-bb3c-4301-ba15-723777b79141.png)

**Comment by ldcsaa** [comment]
https://www.cnblogs.com/ranyonsue/p/5984001.html
![image](https://user-images.githubusercontent.com/5990337/163678831-a757b3ae-6aeb-4930-858f-d81021ffbad0.png)

**Comment by bybaby** [comment]
好吧，虽然还不清楚为什么取不到值，还是要感谢[ldcsaa](https://github.com/ldcsaa)耐心解答！！
