### ISSUE TITLE
CHttpsSyncClientPtr 使用 OpenUrl 请求https 接口 返回错误 1-Operation not permitted

### ISSUE THREAD

**Issue by AdonLuo** [ldcsaa/HP-Socket#223]
你好，博主：
如题：
使用环境：Centos7.9
HP版本：5.8.4  ，其中so 为群里下载使用，未进行自定义编译

简要使用部分代码：
CHttpsSyncClientPtr https(nullptr);
xxxx
if (https->OpenUrl("POST", url.toStdString().c_str(), headers, header_sz, (const BYTE*)req_body.data(), req_body.size()) == FALSE)
{
	auto err = ::SYS_GetLastError();
	auto err_desc = ::SYS_GetLastErrorStr();
        // 错误信息: 1-Operation not permitted
}

结果：url 为 https 时，请求失败，返回错误信息：1-Operation not permitted
请教下博主，这种情况如何定位问题，有什么解决办法？目前不清楚问题出在哪，是so库问题还是使用方法错误导致？谢谢！

**Comment by AdonLuo** [comment]
未进行ssl 环境初始化导致，
最开始报错: 71-Protocol error 是使用了CHttpSyncClientPtr 的对象

**Comment by ldcsaa** [comment]
HTTPS需要初始化SSL环境
