### ISSUE TITLE
OpenUrl应完全转义为UTF-8

### ISSUE THREAD

**Issue by KsaNL** [ldcsaa/HP-Socket#225]
如题 以适应当下大部分网页和请求环境
....
' '->%20
’+‘->%2B
'\n'->%0A

**Comment by ldcsaa** [comment]
可以在调用OpenUrl前进URL编码

**Comment by KsaNL** [comment]
> 可以在调用OpenUrl前进URL编码

内部处理一下吧 或者加一个URLEncode? 我觉得没这个必要

**Comment by ldcsaa** [comment]
可以自己调用HP提供的SYS_URLEncode全局函数。
