### ISSUE TITLE
C#内置UdpClient和HP的UdpClient异常区别问题，发5个请求，HP只收到一个响应

### ISSUE THREAD

**Issue by atfeel** [ldcsaa/HP-Socket#226]
各位，C# 自带的System.Net. Socket的UdpClient发送5个请求给到谷歌DNS，能正常收05个到响应，换成HPSocket的UdpClient 发送相同的5个请求，只能收到第一个的响应，是什么原因呢？

**Comment by FunlyDay** [comment]
这是来自樊  邮箱的自动回复邮件。 您好，您发的邮件我已收到，我会及时查看并予以回复。

**Comment by ldcsaa** [comment]
理论上不会有问题的，是否检查过send的返回值？

**Comment by atfeel** [comment]
已经解决了，谢谢
