### ISSUE TITLE
请教在udparq(kcp)协议下丢包的问题

### ISSUE THREAD

**Issue by qshnqjitx** [ldcsaa/HP-Socket#227]
在做PCM的音频传送，实时要求高，如果有音频数据多次重传还没成功情况下，该数据再发过去已经没多大意义，希望可以在重传次数达到一定阈值时，直接将未传送的数据丢弃。

这种情况下，需要设置哪些参数？需要分别在服务端和客户端分别设置吗？

**Comment by ldcsaa** [comment]
这个比较难，ARQ就是模拟TCP的，数据一定会发送。
你这种情况可以直接用UDP。

**Comment by qshnqjitx** [comment]
在协议上加了序号，在算法上进行了弥补
