### ISSUE TITLE
VS2022 升级后，无法编译

### ISSUE THREAD

**Issue by baidwwy** [ldcsaa/HP-Socket#236]
STLHelper.h(58,23): error C2871: “stdext”: 具有该名称的命名空间不存在

**Comment by ldcsaa** [comment]
自己检查一下配置

**Comment by baidwwy** [comment]
> 

17.4没问题吗，那我重新安装VS试试

**Comment by baidwwy** [comment]
@ldcsaa 确实是有问题，恢复编译器到14.33解决

**Comment by ldcsaa** [comment]
> @ldcsaa 确实是有问题，恢复编译器到14.33解决
在 STLHelper.h 中增加一下头文件引用：
#include <xhash>

**Comment by baidwwy** [comment]
加入 #define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS 就可以了
