### ISSUE TITLE
wss ssl 无法握手成功 不知道为什么

### ISSUE THREAD

**Issue by HotFruits** [ldcsaa/HP-Socket#237]
创建 httpsServer 后 每次创建wss，在SIN_ServerNameCallback 后都会失败 ，而https 访问都能正常进行 ，是不是有什么BUG
都是同一个域名下同一张证书，该证书在nodejs创建的https服务器上没有任何毛病

**Comment by ldcsaa** [comment]
请进Q群描述具体问题。

**Comment by HotFruits** [comment]
已申请
