### ISSUE TITLE
关于在unity中使用il2cpp打包遇上的问题

### ISSUE THREAD

**Issue by SufferYe** [ldcsaa/HP-Socket#240]
我添加了部分dll在unity中跑demo，在编辑器运行时和mono打包正常，但通过il2cpp打包后运行会因为部分委托指向实例方法出现问题
![image](https://user-images.githubusercontent.com/45612437/210038004-1605b63f-d124-4055-ae83-2e30273b030c.png)
目前是否有办法解决/适配？

**Comment by FunlyDay** [comment]
这是来自樊  邮箱的自动回复邮件。 您好，您发的邮件我已收到，我会及时查看并予以回复。

**Comment by int2e** [comment]
il2cpp不支持这种使用方式, 我无法解决.

**Comment by SufferYe** [comment]
好的，感谢回复
