### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ldcsaa/HP-Socket#242]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CClientApp::InitInstance](https://github.com/ldcsaa/HP-Socket/blob/511ab9c8126dc916c7826ac7ea44fd9db8592b4c/Windows/Demo/TestEcho/Client/Client.cpp#L77 "CClientApp::InitInstance function")
- [TPackInfo::Destruct](https://github.com/ldcsaa/HP-Socket/blob/41ad56b108f657e1b8dfa72f6db36fafcf398b92/Windows/Src/MiscHelper.h#L40 "TPackInfo::Destruct function")
- [info_msg](https://github.com/ldcsaa/HP-Socket/blob/511ab9c8126dc916c7826ac7ea44fd9db8592b4c/Windows/Demo/Global/helper.cpp#L43 "Destructor for info_msg")

**Comment by ldcsaa** [comment]
1. That's MFC template code
2/3. Compatible behavior like free(nullptr) and delete nullptr

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by FunlyDay** [comment]
这是来自樊  邮箱的自动回复邮件。 您好，您发的邮件我已收到，我会及时查看并予以回复。
