### ISSUE TITLE
在Qt Creater中使用HPSocket LIB 报错 Error: 3, EC: 11001

### ISSUE THREAD

**Issue by hhbusui** [ldcsaa/HP-Socket#243]
### 问题
大佬们，请问我在Qt Creater中使用HPSocket 时，Start函数总是报错。请问有没有在Qt中使用的例子呢？
Demo中的例子是MFC的，可以在VS中开启字符(支持 MBCS 和 Unicode 字符集)， 但是在Qt中根本找不到开关，请问该怎么处理呢。

### 报错
![image](https://user-images.githubusercontent.com/43135111/211702295-f5ec50dd-daab-4a72-b26f-b716f8f4b079.png)

### 代码
![image](https://user-images.githubusercontent.com/43135111/211702135-595a8e32-6328-4de3-a7d6-4a164764617f.png)

**Comment by Endt4sk** [comment]
QString::toStdWString().c_str()

**Comment by hhbusui** [comment]
好的  多谢 @Endt4sk
