### ISSUE TITLE
自动打印的日志

### ISSUE THREAD

**Issue by Mtr1994** [ldcsaa/HP-Socket#247]
在 Ubuntu x64 平台，编译 5.9.1 ，引入程序后运行，可以连接，但是会自动打印一些消息，这个可以被关闭嘛？

~/Project/AutoWeatherClient/Build$ ./AutoWeatherClient 
  -> [01] /home/mtr1994/Project/hp-socket-5.9.1-src/Linux/lib/hpsocket/x64/libhpsocket.so.5 : (+0xcfc25) [0x7f83a2bf4c25]
  -> [02] /home/mtr1994/Project/hp-socket-5.9.1-src/Linux/lib/hpsocket/x64/libhpsocket.so.5 : (HP_Create_TcpClient+0x26) [0x7f83a2be9196]
  -> [03] ./AutoWeatherClient : (+0x4bd5) [0x55a45f86cbd5]
  -> [04] ./AutoWeatherClient : (+0x2a06) [0x55a45f86aa06]
  -> [05] /lib/x86_64-linux-gnu/libc.so.6 : (__libc_start_main+0xf3) [0x7f83a274a083]
  -> [06] ./AutoWeatherClient : (+0x2b9e) [0x55a45f86ab9e]

**Comment by FunlyDay** [comment]
这是来自樊  邮箱的自动回复邮件。 您好，您发的邮件我已收到，我会及时查看并予以回复。

**Comment by ldcsaa** [comment]
用debug版看看是哪里打印的。
