### ISSUE TITLE
为什么我编译的动态库有Tls Directory

### ISSUE THREAD

**Issue by lwhct** [ldcsaa/HP-Socket#248]
有办法去除这个吗

**Comment by ldcsaa** [comment]
说说你的编译环境，操作步骤，现象

**Comment by lwhct** [comment]
使用VS2019生成HPSocketDLL4C
禁用了UDP,SSL,HTTP,BROTLI
修改afxres.h为winres.h
编译后看PE文件存在
Tls Directory        (线程存储)        	00048D80  	00047780  	00000018  	.rdata

这是为什么
![QQ截图20230430231806](https://user-images.githubusercontent.com/33755338/235361113-17b8be73-0c85-4f0e-b367-0e09061fdbf2.jpg)

**Comment by ldcsaa** [comment]
这个没注意，应该不影响使用。
