### ISSUE TITLE
unity中使用HPSocket.Net (C# 版)  il2cpp打包遇上的问题

### ISSUE THREAD

**Issue by lovehou922** [ldcsaa/HP-Socket#251]
unity中使用HPSocket.Net (C# 版) 导入HPSocket4C.dll 
使用il2cpp打包 win64平台，报错
![20230423-161643](https://user-images.githubusercontent.com/13890768/233828428-498ac7c5-f711-4be2-9130-9481bdf06d3b.jpg)

**Comment by int2e** [comment]
应该是il2cpp不支持委托设置回调到原生代码, 解决不了
