### ISSUE TITLE
EnumHostIPAddresses 在安卓无效

### ISSUE THREAD

**Issue by baidwwy** [ldcsaa/HP-Socket#252]
在PC有用，取的是本地列表

使用SDL正常 
https://github.com/libsdl-org/SDL_net/blob/1dd4e9578a0fb8ee4ebbb1faa6ada39955acb7db/SDLnet.c#L221

**Comment by ldcsaa** [comment]
应该是忘记修改 ai_flags 参数了
https://github.com/ldcsaa/HP-Socket/blob/eb815a839cea65e5a21455628f91b55416336d74/Linux/src/SocketHelper.cpp#LL180C6-L180C6
这个文件有两个地方调用getaddrinfon(）,你根据第一个调用的设置修改一下第二个调用的参数试试
