### ISSUE TITLE
client如何通过http代理方式连接server？

### ISSUE THREAD

**Issue by JimmyDemo** [ldcsaa/HP-Socket#255]
你好，使用5.9.1版本时，参考文档Q-18和Q-19还是没理解如何通过http代理连接服务器，希望有时间能够解答一下，谢谢
（1）使用SSL client可以正常连接SSL server并收发消息，但是如何通过 ssl client-> http -> ssl server 方式还请帮忙解答一下
（2）Q-19所说的特殊连接地址格式<hostaddress>^<hostname>，是用start接口吗？  <hostaddress>是以<ip:port>方式书写吗？

**Comment by ldcsaa** [comment]
1、HTTP代理只支持HTTP Client，TCP Client 只能使用Socks代理
2、client.Start(目标服务器域名^代理IP地址, 端口)

**Comment by JimmyDemo** [comment]
先关闭ssl自动握手，使http代理与目标SSL服务器建立连接后，再使SSLclient进行握手即可成功
