### ISSUE TITLE
RWLock版本错误

### ISSUE THREAD

**Issue by woowloop** [ldcsaa/HP-Socket#258]
在RWLock文件中TryAcquireSRWLockShared函数是win7及以上才支持 而宏的判断最小是6.0

**Comment by ldcsaa** [comment]
_WIN32_WINNT_WIN6		0x0600
_WIN32_WINNT_VISTA		0x0600
_WIN32_WINNT_WS08		0x0600
_WIN32_WINNT_LONGHORN	0x0600
_WIN32_WINNT_WIN7		0x0601
_

**Comment by ldcsaa** [comment]
synchapi.h 中定义的是
```
#if (_WIN32_WINNT >= 0x0600)
```

但好像有bug：
https://stackoverflow.com/questions/49317541/tryacquiresrwlock-and-win32-winnt
