### ISSUE TITLE
ucrt.lib(api-ms-win-crt-heap-l1-1-0.dll) : error LNK2005: _malloc 已经在 HPSocket.lib(jemalloc.obj) 中定义

### ISSUE THREAD

**Issue by JimmyDemo** [ldcsaa/HP-Socket#261]
在HPSocketLIB配置运行库为MD后，生成Release静态库后，在引用HPSocket.lib时，报错
1>ucrt.lib(api-ms-win-crt-heap-l1-1-0.dll) : error LNK2005: _free 已经在 HPSocket.lib(jemalloc.obj) 中定义
1>ucrt.lib(api-ms-win-crt-heap-l1-1-0.dll) : error LNK2005: _realloc 已经在 HPSocket.lib(jemalloc.obj) 中定义
1>ucrt.lib(api-ms-win-crt-heap-l1-1-0.dll) : error LNK2005: _calloc 已经在 HPSocket.lib(jemalloc.obj) 中定义
1>ucrt.lib(api-ms-win-crt-heap-l1-1-0.dll) : error LNK2005: _malloc 已经在 HPSocket.lib(jemalloc.obj) 中定义

只有release模式下会出现此问题，请问该怎样解决？

**Comment by redapples2008** [comment]
我也遇到了该问题，目前还没找到解决方法。 求指点

**Comment by ldcsaa** [comment]
静态库应该用mt编译

**Comment by JimmyDemo** [comment]
解决方案: 采用强制链接器做法按照正确顺序链接, 通过在Properties-Configuration Properties->Linker->Command Line设置参数： /FORCE:MULTIPLE
