### ISSUE TITLE
UDP 丢包

### ISSUE THREAD

**Issue by boyucjz** [ldcsaa/HP-Socket#262]
使用的是 HP-Socket-5.5.3 这个版本 ， 使用 UdpServer 接收数据包， 发现有时候某个IP的数据包无法接收（使用tcpdump进行抓包能抓到） ，大约从500多个IP接收数据。一旦出现这种情况，这个IP的数据包就无法处理， 其它IP的数据包可以正常处理。 重启软件后，那个IP的数据包就能处理了。 请问题这种问题一般从哪方面分析？

**Comment by ldcsaa** [comment]
1、丢包是UDP的特性
2、最新版本对减少丢包作了优化
3、增大接收缓冲区可减少丢包

**Comment by boyucjz** [comment]
找到问题了，是因为有一个IP一直用随机端口号给服务器发送数据包引起的，   运行半个月后，无法接收新连接了。
