### ISSUE TITLE
VS2015单文档程序静态编译用release-win32调试，会报错（使用VS2015编译的release静态库HPSocketLIB）

### ISSUE THREAD

**Issue by wgwjifeng** [ldcsaa/HP-Socket#263]
VS2015单文档程序静态编译用release-win32调试，会报错（使用VS2015编译的release静态库HPSocketLIB）
 	ntdll.dll!_RtlSizeHeap@12()	未知
>	DanWenDang.exe!_msize(void * block=0x00590000) 行 34	C++
 	DanWenDang.exe!AfxUnlockTempMaps(int bDeleteTemps=0x00000001) 行 56	C++
 	DanWenDang.exe!CWinThread::OnIdle(long lCount=0x00000001) 行 720	C++
 	DanWenDang.exe!CWinApp::OnIdle(long lCount=0x00000001) 行 1075	C++
 	DanWenDang.exe!CWinThread::Run() 行 621	C++
 	DanWenDang.exe!AfxWinMain(HINSTANCE__ * hInstance=0x013b0000, HINSTANCE__ * hPrevInstance=0x00000000, wchar_t * lpCmdLine=0x00683bcc, int nCmdShow=0x0000000a) 行 47	C++
 	DanWenDang.exe!__scrt_common_main_seh() 行 253	C++
 	kernel32.dll!@BaseThreadInitThunk@12()	未知
 	ntdll.dll!___RtlUserThreadStart@8()	未知
 	ntdll.dll!__RtlUserThreadStart@8()	未知

**Comment by ldcsaa** [comment]
解决办法：
1、升级到最新版
2、如果还不行就移除 jemalloc 再重新编译
