### ISSUE TITLE
UDP通讯日志错误求助

### ISSUE THREAD

**Issue by boyucjz** [ldcsaa/HP-Socket#265]
![2](https://github.com/ldcsaa/HP-Socket/assets/18730041/060bd013-8f28-42bf-a8cc-7226075932f4)
问题1：请问上图中的   onError   OP:4  CODE:90   代表什么错误，  是否需要处理？ 
问题2： OnAccept  前的序号  一直变大，  请问是否需要处理，达到一定数值后是不是就无法连接了，   使用的是UdpServer    接收数据

**Comment by ldcsaa** [comment]
90 表示接收到了超过限定长度的数据包
