### ISSUE TITLE
Invalid request code 然后程序崩溃

### ISSUE THREAD

**Issue by kisstea** [ldcsaa/HP-Socket#270]
错误如下：

(#332145, 2157269344) > exit(70) [56] : Invalid request code
HPSocket/socket/../common/Event.h (272) : CCounterEvent<is_sem_mode>::CCounterEvent(int) [with bool is_sem_mode = false]

**Comment by kisstea** [comment]
CCounterEvent(int iInitCount = 0)
        {
                int iFlag       = EFD_NONBLOCK | EFD_CLOEXEC | (is_sem_mode ? EFD_SEMAPHORE : 0);
                m_evt           = eventfd(iInitCount, iFlag);

                VERIFY(IsValid()); // 这一句
        }

我现在参考其他issue先尝试去掉 VERIFY

**Comment by ldcsaa** [comment]
你看看eventfd调用的errcode是什么。然后查看这个函数的API文档
