### ISSUE TITLE
无法启动服务器。( The listener will not start.)

### ISSUE THREAD

**Issue by yangsungyeol** [ldcsaa/HP-Socket#272]
return Sdk.Server.HP_Server_Start(SenderPtr, Address, Port); 从这部分返回 false。

间歇性问题 
重启系统会使问题消失。
当接收器无法启动时，无法确定原因。

 The listener will not start.

The server start method returns False.

The ip and port passed through fine, but I can't determine why.
Rebooting the computer sometimes improves things.

It is Windows 11 , I have Norton 360 personal firewall but it stops and uses it.

**Comment by yangsungyeol** [comment]
I tried many times, but , 
I have not had any problems with firewall programs.

When the PC is turned on , run visual studio and check the results , Sdk.Server.HP_Server_Start(SenderPtr, Address, Port) returns True regardless of the firewall.

The problem is that when it returns False, I don't know the reason for the error.

If it returns False, restarting HP_Server_Start, retrying, quitting Visual Studio, or restarting the program will not resolve the issue.

rebooting the PC sometimes works.

When the server fails to start, is there an error message or any way to know why?

**Comment by yangsungyeol** [comment]
errorCode : SocketBind 
erroeMessage : "Bind SOCKET Fail"

Message received.
![2023-10-31_13h00_45](https://github.com/ldcsaa/HP-Socket/assets/5600019/c209f7a3-272b-447b-a1e8-6f6e4aa3d7d5)

**Comment by yangsungyeol** [comment]
When the socket server failed to start, I disabled all unused network adapters on my PC network connection.

Then the server started successfully.

I think this might be a hint to solve the problem.


当套接字服务器无法启动时，我禁用了电脑网络连接上所有未使用的网络适配器。

然后服务器就成功启动了。

我想这可能是解决问题的一个提示。
![2023-10-31_13h23_35](https://github.com/ldcsaa/HP-Socket/assets/5600019/1f1336bc-5b4e-43a7-98c8-1867ec87efd1)
![2023-10-31_13h28_26](https://github.com/ldcsaa/HP-Socket/assets/5600019/324803a2-b75b-40b5-96fa-35f102df16c9)

**Comment by ldcsaa** [comment]
When start fail, uses `Server.GetLasterror()` and `SDK.SYS_GetLastError()` to obtain component error code and system errorcode.

System errorcode  would explain why "Bind SOCKET Fail", maybe Port in used, address not exists etc.

**Comment by yangsungyeol** [comment]
感谢你的努力工作Android용 Outlook 다운로드

**Comment by ldcsaa** [comment]
看看是配置的IP，网段是否有重叠。

**Comment by yangsungyeol** [comment]
> 绑定为 0.0.0.0 会有这个问题吗?

无论我从哪个目镜开始，情况都是一样的。

0.0.0.0 , 192.168.0.87 , 127.0.0.1 

交换端口时也是如此。

重启和重启电脑时也是一样、 
我的电脑上有几个未使用的网络适配器，我把它们都禁用了，问题就解决了。

**Comment by yangsungyeol** [comment]
> 看看是配置的IP，网段是否有重叠。

我的开发机使用 DHCP，所以这不是系统配置问题。

在某些情况下，绑定不起作用，禁用未使用的网络适配器后问题就解决了。

将来，我希望能指定某个适配器开始监听套接字。

**Comment by yangsungyeol** [comment]
目前，我通过禁用不必要的网络适配器解决了这个问题。

如果有任何改进，请告诉我。

**Comment by ldcsaa** [comment]
试试重置一下协议栈：
netsh int ip reset
netsh winsock reset
重启机器。
