### ISSUE TITLE
能否加入zstd压缩库

### ISSUE THREAD

**Issue by SnowMeteors** [ldcsaa/HP-Socket#278]
https://github.com/facebook/zstd
zstd压缩库链接如上

**Comment by ldcsaa** [comment]
HP和压缩没有多大关系，你自己引入这个库就好。

**Comment by btx638** [comment]
> HP和压缩没有多大关系，你自己引入这个库就好。

能否新增发布一个以下要求的版本呢？
_ZLIB_DISABLED ：排除 zlib 相关功能函数。
_BROTLI_DISABLED ：：排除 brotli 相关功能函数。

**Comment by btx638** [comment]
> HP和压缩没有多大关系，你自己引入这个库就好。

能否新增发布一个不带任何压缩库的版本呢？
_ZLIB_DISABLED ：排除 zlib 相关功能函数。
_BROTLI_DISABLED ：：排除 brotli 相关功能函数。

**Comment by ldcsaa** [comment]
> > HP和压缩没有多大关系，你自己引入这个库就好。
> 
> 能否新增发布一个不带任何压缩库的版本呢？ _ZLIB_DISABLED ：排除 zlib 相关功能函数。 _BROTLI_DISABLED ：：排除 brotli 相关功能函数。

自己修改 HPTypeDef.h 头文件重新编译即可。
