### ISSUE TITLE
C#版SSL Demo需要更新了

### ISSUE THREAD

**Issue by BrillianceRen** [ldcsaa/HP-Socket#28]
5.0.1调整SSL相关函数后，C#相关Demo没有更新。
同时希望HPSocket类库SSL编译能支持VS2012以上版本，目前用VS2017编译提示
 fatal error C1083: 无法打开包括文件: “SDKDDKVer.h”: No such file or directory

**Comment by ldcsaa** [comment]
1、看看5.0.2
2、高版本IDE编译看Readme.txt

**Comment by ldcsaa** [comment]
第一个问题5.1.1已修复，即将发布
