### ISSUE TITLE
流式数据压缩 怎么用呀

### ISSUE THREAD

**Issue by SnowMeteors** [ldcsaa/HP-Socket#281]
作者能不能写一个demo呀，pdf文档完全不懂咋用

**Comment by ldcsaa** [comment]
demo

**Comment by SnowMeteors** [comment]
> Uploading 流式压缩-解压示例.zip… demo

这链接点了没用，没上传上去

**Comment by ldcsaa** [comment]
[流式压缩-解压示例.zip](https://github.com/ldcsaa/HP-Socket/files/14076307/-.zip)
