### ISSUE TITLE
解压算法出错，解压数据不能正确处理

### ISSUE THREAD

**Issue by SnowMeteors** [ldcsaa/HP-Socket#284]
这是我的测试代码
``` c++
#include <iostream>
#include <algorithm>
#define HPSOCKET_STATIC_LIB
#include "HPSocket/HPSocket-SSL.h"

#pragma comment(lib,"HPSocket/HPSocket_UD.lib")

static BOOL __HP_CALL OnDecompressData(const BYTE* pData, const int iLength, const PVOID pContext = nullptr)
{
	std::cout << "解压的大小为 " << iLength << "\n";
	return true;
}

int main()
{
	IHPDecompressor* m_PDecompressor = HP_Create_BrotliDecompressor(OnDecompressData);

	// 随便写的数据 容错率测试
	//constexpr BYTE data[] = { 0x47,0x58 };	// 测试这行什么都不输出 程序应该输出解压失败
	constexpr BYTE data[] = { 0x11,0x12 };		// 测试这行 程序输出解压失败

	constexpr int iLength = sizeof(data);

	constexpr size_t maxBatchSize = 4096;
	constexpr auto dataSize = static_cast<size_t>(iLength);

	for (size_t i = 0; i < dataSize; i += maxBatchSize)
	{
		const auto length = static_cast<int>(std::min<size_t>(dataSize - i, maxBatchSize));
		if (!m_PDecompressor->Process(data + i, length))
		{
			std::cout << "解压失败\n";
			break;
		}
	}
        HP_Destroy_Decompressor(m_PDecompressor);
	return 0;
}
```
当测试数据为 `constexpr BYTE data[] = { 0x11,0x12 };` 程序按我的预期执行
![image](https://github.com/ldcsaa/HP-Socket/assets/47601098/bc1b4387-826e-4788-aebf-7ce79691d8b0)

当测试数据为 `constexpr BYTE data[] = { 0x47,0x58 };`  程序结果什么都没有输出，我预期它应该输出解压失败。这是为什么呢？
![image](https://github.com/ldcsaa/HP-Socket/assets/47601098/849e5f78-964a-47ac-84a4-2be16f2bf6e8)

**Comment by ldcsaa** [comment]
//constexpr BYTE data[] = { 0x47,0x58 };	// 测试这行什么都不输出 程序应该输出解压失败
- 数据格式正确，等待后续数据。

//constexpr BYTE data[] = { 0x11,0x12 };		// 测试这行 程序输出解压失败
- 数据格式不正确，立刻返回失败。

**Comment by ldcsaa** [comment]
> > //constexpr BYTE data[] = { 0x47,0x58 }; // 测试这行什么都不输出 程序应该输出解压失败
> > 
> > * 数据格式正确，等待后续数据。
> > 
> > //constexpr BYTE data[] = { 0x11,0x12 }; // 测试这行 程序输出解压失败
> > 
> > * 数据格式不正确，立刻返回失败。
> 
> 如果是这样的话，恰好碰到这种人为构造的脏数据，也就是 `数据格式正确，等待后续数据`。 怎么办呢，这种情况又不算解压成功，又不算解压失败。对于一段待解压的数据，岂不是很不合理？

流式解压就是这样的特性。

**Comment by SnowMeteors** [comment]
我还是建议加入zstd压缩算法，目前性价比都很好的算法，内存低，压缩率高，速度又快，至少比现在hp socket的提供的压缩库来比的话
