### ISSUE TITLE
X86 無法使用

### ISSUE THREAD

**Issue by stevenweis** [ldcsaa/HP-Socket#295]
請問一下平台目標 X86 底下 會出錯要如何處理呢
![螢幕擷取畫面 2024-09-19 142529](https://github.com/user-attachments/assets/17f525e7-7a2c-4418-9b0f-743f58c97c12)

**Comment by FunlyDay** [comment]
这是来自樊  邮箱的自动回复邮件。 您好，您发的邮件我已收到，我会及时查看并予以回复。

**Comment by stevenweis** [comment]
您好, 問題已解決謝謝!  引用錯誤的HPSocket4C.dll
