### ISSUE TITLE
连接异常断开

### ISSUE THREAD

**Issue by walking-with-linght** [ldcsaa/HP-Socket#297]
前后端均使用hpsocket库 使用tcp连接，C#语言开发。

服务端放在家里的小主机，使用frp跟云服务器建立中转。
比如：服务器监听10000端口，使用frp将本地10000端口转发到云服务器的10001端口。

客户端在公司电脑启动，连接云服务器的10001端口可以跟家里服务端通信，但5分钟左右客户端提示断开连接，（触发了OnClose事件）

因为特殊原因才这样部署，如果服务端直接部署到云服务器是没问题的。

另外: 在hpsocket提issue是因为，我还启动了另一个tcp程序（没有使用hpsocket），采用同样的部署模式（frp+云服务器中转），同样在公司一样的网络一样的电脑，tcp连接并没有断开。

hpsocket版本为5.8.3.1

**Comment by int2e** [comment]
可以尝试每50秒至少发一个包作为保活包试一下

**Comment by ldcsaa** [comment]
1、问题是否必现？
2、是否有地方主动断开连接
3、可以进群详细描述问题

**Comment by walking-with-linght** [comment]
> 可以尝试每50秒至少发一个包作为保活包试一下

谢谢，已解决，确实是这问题，我以为hpsocket有自己的一套保活机制。

**Comment by ldcsaa** [comment]
是不是你的frp配置问题？自动断开空闲连接。
