### ISSUE TITLE
RingBuffer.h 函数问题

### ISSUE THREAD

**Issue by LYCUESTC** [ldcsaa/HP-Socket#31]
LZ您好！
RingBuffer.h 中下面这个函数EmplaceIndex，主要作用干啥的呢？当客户端连接到服务器这边的时候，走到m_indexes.emplace(dwIndex);一直报错。
void EmplaceIndex(index_type dwIndex)
	{
		CWriteLock locallock(m_cs);
//		m_indexes.emplace(dwIndex);
	}

**Comment by ldcsaa** [comment]
自己好好检查代码，不可能这里出错。
