### ISSUE TITLE
使用C#版WebSocketServer遇到一个问题

### ISSUE THREAD

**Issue by chen365409389** [ldcsaa/HP-Socket#33]
我在使用C#版HPSocket的WebSocketServer时遇到一个问题，如果WebSocket客户端连接服务端后，向服务端发送过消息，服务端就可以正常向客户端回复消息，但是当WebSocket客户端连接上服务端后，没有向服务端发送过消息之前，服务端向客户端发送消息就会出现异常，具体调试及复现过程已经上传至附件中，还请大神在百忙中解决一下，万分感谢！
[HPSocketCS调试.zip](https://github.com/ldcsaa/HP-Socket/files/1566965/HPSocketCS.zip)

**Comment by ldcsaa** [comment]
看看是否触发了OnUpgrade，如果没触发则说明没完成WebSocket握手。

**Comment by chen365409389** [comment]
![upgrade](https://user-images.githubusercontent.com/12838089/34185954-7f9b58a0-e563-11e7-8906-0fac86ee4815.png)
触发了Upgrade事件，并且进行了返回。

**Comment by ldcsaa** [comment]
那就没问题了呀，随时可以用SendWSMessage发消息了，只需注意mask参数必须为空。

**Comment by ldcsaa** [comment]
pServer->SendWSMessage(dwConnID, TRUE, 0, 1, nullptr, (LPBYTE)(LPCSTR)"123,ABC.", 8);

注意第二和第五个参数。

**Comment by chen365409389** [comment]
我在服务端调用SendWSMessage方法时，直接使用你提供的这些参数现在可以发送了，但是我之前看Demo里面是调用了GetWSMessageState来获取final,reserved,operationCode相关内容，然后传给SendWSMessage方法的，GetWSMessageState方法是必须的吗？还有我跟踪了下GetWSMessageState方法，如果客户端发送过消息，服务端调用该方法返回是正常的，如果客户端只是连接并且升级完协议，没有发送过消息之前，服务端调用GetWSMessageState取到的值就不对了，是需要做什么判断吗？

**Comment by ldcsaa** [comment]
好好研究ws协议，看看这些参数是什么含义。

**Comment by ldcsaa** [comment]
GetWSMessageState只有在websocket事件处理函数中调用才有意义。

**Comment by chen365409389** [comment]
好的，我再好好学习ws协议，谢谢啦
