### ISSUE TITLE
Delphi 7 測試 issue

### ISSUE THREAD

**Issue by zadehalex** [ldcsaa/HP-Socket#34]
開發環境:

Win8.0 + Delphi7:
  TcpServer / Client : 可以成功編譯與執行

Win10 + Delphi7:
  TcpServer: 可以成功編譯與執行
  Client: 可以成功編譯,執行 connect 時 show error:
  Access violation at address 61B0E876 in module 'HPSocket4C.dll'. Read of address 00000004
  <-- 很奇怪!

另外: Http sample:
Win8.0 + Delphi7:
  Http sample: 編譯不過 error 在 
    function OnRequestLine(pSender: HP_Http; ...
       Request[0].name:= PChar('Content-Type');       
       Request[0].value:= PChar('text/html');
       Request[1].name:= PChar('Connection');
       Request[1].value:= PChar('Keep-Alive');

   HPTypeDef.pas  原始碼:
  {/*****名称：Name/Value 结构体 描述：字符串名值对结构体 **/}
  TNVPair = array of array of PChar;   //好像沒宣告 好像沒有宣告型態
  implementation
  end.

Win10 + Delphi7:
  Http sample: 未測

**Comment by ldcsaa** [comment]
到群里提问吧
怪兽乐园②群：44636872
