### ISSUE TITLE
Agent场景中，connID赋值返回应该在HP_Set_FN_Agent_OnConnect事件之前

### ISSUE THREAD

**Issue by weixiao5** [ldcsaa/HP-Socket#36]
Agent场景中，connID赋值返回应该在Sockect_On_Agent_Accept事件之前

在HP_Agent_Connect连接方法中，传参数后，ConnID 连接ID 参数回调返回比 HP_Set_FN_Agent_OnConnect 连接回调函数慢，导致 agent发起连接的ConnId无效 无法再OnConnect方法中给与状态改变

建议：先在Hp_Agent_Connect 中先返回ConnId 然后在执行OnConnect事件回调

**Comment by ldcsaa** [comment]
嗯，下个版本改改。
