### ISSUE TITLE
c#demo中SSLHttpServer.cs第二次开始服务出错

### ISSUE THREAD

**Issue by jiongge** [ldcsaa/HP-Socket#37]
SSLHttpServer创建时调用了一次Interlocked.Increment(ref ObjectReferer);
可是每次Uninitialize的时候都调用了 if (Interlocked.Decrement(ref ObjectReferer) == 0 && pServer != IntPtr.Zero)
而每次开始服务的时候都会调用Uninitialize，这样就导致Interlocked.Decrement(ref ObjectReferer) == 0返回false，从而不能调用SSLSdk.HP_SSLServer_CleanupSSLContext(pServer);
再次开始服务时候Initialize服务返回false

**Comment by sankeyou** [comment]
最新版本已更新
`https://gitee.com/int2e/HPSocketCS`
现在需要手动调用Initialize()和 Uninitialize()方法，具体请查看demo

**Comment by ldcsaa** [comment]
最新版本代码：[https://gitee.com/int2e/HPSocketCS](https://gitee.com/int2e/HPSocketCS)
下次发布将纳入。
