### ISSUE TITLE
如何创建cer证书？

### ISSUE THREAD

**Issue by mangox** [ldcsaa/HP-Socket#39]
老哥，能否提供一下测试环境中SSL证书创建的步骤或者命令及工具？
谢谢～

**Comment by gallimaufrystew** [comment]
install openssl

**Comment by ldcsaa** [comment]
方法：
1、安装openssl，根据网上教程创建私有证书
2、去阿里云、腾讯云等地方申请一个免费证书

**Comment by mangox** [comment]
谢谢，已经安装完成了。项目已经用自己的密钥部署了。谢谢老哥，项目太棒了。

**Comment by kingflyok** [comment]
> 谢谢，已经安装完成了。项目已经用自己的密钥部署了。谢谢老哥，HPSocket太棒了。

请教一下如何生成的 我用openssl一直生成出来的 无法加载成功
