### ISSUE TITLE
[Bug] v5.2.1中TCPPackClient连接成功SSLPackServer

### ISSUE THREAD

**Issue by mangox** [ldcsaa/HP-Socket#40]
**HPSocket版本**
v5.2.1
**Bug描述**
无论有无证书，TCPPackClient居然可以成功连接上SSLPackServer；理论上握手这一步都不能完成。当client给server发消息后，server才能发生错误并中断连接。
**潜在影响**
当用户从TCPPackClient迁移到SSLPackClient时，一些老的TCPPackClient仍然可以成功连接上SSLPackServer。
**Bug截图**
![hpsocket_bug](https://user-images.githubusercontent.com/12643640/37909915-cf93a476-313e-11e8-804a-0b8a80bbe5cd.jpg)

**Comment by mangox** [comment]
@ldcsaa 老哥，看一下这个是不是一个问题。还是我SSL初始化时候设置的SSLVerifyMode 有问题。
SSLPeer | SSLFailIfNoPeerCert

**Comment by ldcsaa** [comment]
连接时TCP层的事，跟 SSL 没有一毛钱关系~
例如你可以 telnet www.baidu.com 443

**Comment by mangox** [comment]
嗯，我原也是这么想的。。。多谢大佬解惑
