### ISSUE TITLE
c#封装SDK_OnSend SDK_OnReceive 崩溃问题

### ISSUE THREAD

**Issue by jiongge** [ldcsaa/HP-Socket#41]
在TcpServer.cs中SDK_OnSend和SDK_OnReceive中，如果参数pData为null会导致 Marshal.Copy(pData, bytes, 0, length);崩溃，我添加if (length > 0)后能解决这个问题

我只用到了TcpServer.cs，其他封装代码中也应该会出现这个问题
protected HandleResult SDK_OnSend(IntPtr pSender, IntPtr connId, IntPtr pData, int length)
        {
            if (OnSend != null)
            {
                byte[] bytes = new byte[length];
                if (length > 0)
                {
                    Marshal.Copy(pData, bytes, 0, length);
                }
                return OnSend(connId, bytes);
            }
            return HandleResult.Ignore;
        }

        protected HandleResult SDK_OnReceive(IntPtr pSender, IntPtr connId, IntPtr pData, int length)
        {
            if (OnPointerDataReceive != null)
            {
                return OnPointerDataReceive(connId, pData, length);
            }
            else if (OnReceive != null)
            {
                
                byte[] bytes = new byte[length];
                if (length > 0)
                {
                    Marshal.Copy(pData, bytes, 0, length);
                }   
                return OnReceive(connId, bytes);
            }
            return HandleResult.Ignore;
        }

**Comment by ldcsaa** [comment]
pData不可能为null的，应该是你代码有问题，如有问题请进QQ群里发问。

**Comment by shenzhigang** [comment]
@ldcsaa  QQ群是什么？没有搜索到HP-socket的群
