### ISSUE TITLE
建议：TcpPullServer增加一个"查找byte序列"的HP_TcpPullServer_Find()方法

### ISSUE THREAD

**Issue by gmxyb** [ldcsaa/HP-Socket#45]
目前只能每次用 HP_TcpPullServer_Peek 先取出来自己在临时的buffer中查找分隔符，多了很多无效的内存拷贝。

建议提供一个可以直接在内部缓冲区查找特定BYTE序列的函数，这样就不需要全部Peek出来了。

int HP_TcpPullServer_Find(HP_TcpPullServer pServer, HP_CONNID dwConnID, BYTE* pFind, int iLength);

pFind是需要匹配的序列, iLength 是pFind 的字节数（必须>=1）

返回值：如果 >0 表示匹配到了，可以Fetch的字节数（包含末尾的pFind），如果 <=0 则未找到

**Comment by ldcsaa** [comment]
可能你使用pull的方式有问题，正常情况下只要你的应用层协议定义得合理（包头包体清晰）是不需要调用HP_TcpPullServer_Peek方法的。可参考相关示例DEMO。

**Comment by gmxyb** [comment]
谢谢回答。我遇到的是别人定的不定长协议。。

**Comment by ldcsaa** [comment]
不定长也可以用PULL，只要包头能拿到包体的长度

**Comment by gmxyb** [comment]
大哥，就是因为包头也不定长，不然我也不会提这个了。。

**Comment by ldcsaa** [comment]
如果不同包类型的包头长度固定或包头的最前字节为包类型和包头长度还好处理，可以对包头进行二次解析。否则只能自己处理了，或者直接用PUSH模型。
