### ISSUE TITLE
Client的GetConnectionID函数返回的不是实际id

### ISSUE THREAD

**Issue by JiangWang01** [ldcsaa/HP-Socket#46]
调用client的GetConnectionID函数返回1，而不是实际在server端分配的id。我现在的做法是连接后还要从server端发送client实际的id给client。建议修复GetConnectionID返回错误id问题

**Comment by ldcsaa** [comment]
每个组件有自己的CONNID体系，互补相干。

**Comment by JiangWang01** [comment]
@ldcsaa 如果这样的话，设计client的GetConnectionID函数应该作用就不大了吧，只会返回1或者0，按正常逻辑理解这个函数不是应该返回与服务端连接的实际id吗。比如TcpClient又不像Agent，不需要与其他client相连，只与TcpServer相连，调用TcpClient的GetConnectionID函数难道不应该返回TcpServer分配的实际ID吗。我用HPSocket做游戏服务器，想用GetConnectionID函数直接得到Client的实际连接ID

**Comment by ldcsaa** [comment]
Client的CONNID每次Start递增。对Client来说CONNID意义确实不大，只是作个标识为了接口统一
