### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ldcsaa/HP-Socket#47]
I would like to point out that identifiers like “[`_Creator`](https://github.com/ldcsaa/HP-Socket/blob/73c919b4ec0727e76aa214bc79210d2758a7f059/Linux/include/hpsocket/HPSocket.h#L66 "Update candidate")” and “[`__super`](https://github.com/ldcsaa/HP-Socket/blob/73c919b4ec0727e76aa214bc79210d2758a7f059/Linux/src/common/StringT.h#L39 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by ldcsaa** [comment]
Source code of Windows And Linux are separated absolutely. On Linux/GCC platform, __super is defined like 'using __super = T'.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
