### ISSUE TITLE
tcppack的maxpacksize问题

### ISSUE THREAD

**Issue by Febfire** [ldcsaa/HP-Socket#49]
maxpacksize最大可以设置多大？
我发送几十K的小文件没问题，几百K的就连receive事件都不会触发了。(默认没有设置maxpacksize)
当我设置maxpacksize=0x1000之后依然无效，这个0x1000的单位是K吗？
求解答

**Comment by ldcsaa** [comment]
文档里有详细说明

XXXXXXXXXX YYYYYYYYYYYYYYYYYYYYYY

前 10 位 X 为包头标识位， 用于数据包校验。有效包头标识取值范围 0 ~ 1023 （ 0x3FF），
当包头标识等于 0 时不校验包头。 后 22 位 Y 为长度位，记录包体长度。 有效数据包最大
长度不能超过 4194303（ 0x3FFFFF） 字节，默认长度限制为： 262144（ 0x40000）字节。 应
用程序可以通过 SetPackHeaderFlag() 和 SetMaxPackSize() 分别设置包头标识与最大包长限
制。
