### ISSUE TITLE
issue about how to wrap class 

### ISSUE THREAD

**Issue by lionm117** [ldcsaa/HP-Socket#5]
to respect the culture of github and honor this project , i would like to express myself with english . 

HP-socket  is a wonderful lib , which could help to solve lots of problems in my work . like the heart-beat  mode  , efficiency of communication  . 
as a C++ programmer  ,  i had been trapped in  C++ for many years  in the network communication . when i met issues , i tried  to find a proper libs to solve my problems . when  the solution seemed not work very well .  failed fellow . . (as  lots of my work is dealing with  low computer communication which is base on the TCP/UDP  byte string  exchange) . 
as there were no proper libs which could meet my requirement  , so i became to learn how to wrap the class for myself , so i engaged the technique  design pattern , refactory  , FP ect . it seemed work for me , as it  was promoted my work efficiency  . 
however  when i tried  to take this technique on the network  , i was frustrated a lot , there were so many kind of condition that i had never take into consideration  . the exceptions and  issues were out of my control . i felt so depressed . 
when i noticed this project , i found you were a great software developer  . when you met your problems , you solved . that was no surprise . so  did everyone  
but what attracted me was that you could abstracted the common function and wrapped them  gracefully  and  efficient . at the same time , you distributed your source code to the public  , may you work could help more people .  that was wonderful and  respectful . 
i would like to do that like you did .  i think programming is to help people to solve problems . but i was confused  .
 could you  share  some tips  or  suggestions  about: how  to wrap class more efficient and gracefu   ?? 
(wrap  class efficient and gracefully  ,  especially  in the aspect of  wrapping   network class )
on the way wrapping API  , i knew i was almost there , but i found i was trapped . could you do me a favor ?  
chinese would be ok for me ,    
appropriate   
contact :   lion_117@126.com

**Comment by ldcsaa** [comment]
简单说说吧：
1、站在使用者的角度设计接口
2、掌握平衡，易用性、性能、复杂性等
3、设计应从外到内、从上到下，从概要到详细逐步进化
5、不断对代码进行重构
6、设计模式、设计原则等是工具，学习是必要的，当需要时能拾起工具进行工作，但有了工具还需要灵活运用
