### ISSUE TITLE
TcpClient连上服务器后，收不到数据，发数据对方也收不到。

### ISSUE THREAD

**Issue by crisidoff** [ldcsaa/HP-Socket#51]
使用C#版本的封装，使用TcpClient连上服务器后，收到服务器链接成功事件，开始发送数据，显示发送成功，但对方未收到，对方给本地发数据，也收不到。隔一定时间后，收到一大包数据。 测试环境: 联想E570 win7 64位和华为V3 windows server 2008R2，物理网卡虚拟网卡都测试过，均存在这个问题。另外还有一台联想台式机Win7 64位测试没出现这个问题。

**Comment by ldcsaa** [comment]
异步连接要收到OnConnect或OnHandShake事件后算连接成功，才能发送数据。
