### ISSUE TITLE
关于心跳包的问题

### ISSUE THREAD

**Issue by anheiqq** [ldcsaa/HP-Socket#52]
使用版本：5.2.1
TCP心跳包检测机制：
超时间计算公式： KeepAliveTime + (KeepAliveInterval * N)
其中 N为固定值：  WinXP以下系统 N=5 ；Win7 以上系统 N=10

使用的相关函数说明：
/* 设置正常心跳包间隔（毫秒，0 则不发送心跳包，默认：30 * 1000） */
virtual void SetKeepAliveTime		(DWORD dwKeepAliveTime)			= 0;
/* 设置异常心跳包间隔（毫秒，0 不发送心跳包，，默认：10 * 1000，如果超过若干次 [默认：WinXP 5 次, Win7 10 次] 检测不到心跳确认包则认为已断线） */
virtual void SetKeepAliveInterval	(DWORD dwKeepAliveInterval)		= 0;

通过尝试 这两个函数的参数值只有设置成1000以上时才能Start TcpSocket Server成功， 这样的话至少10秒左右才能检测到断线， 这对于客户端连接数量不高，实时性要求高的场景检测断线的时间就有点长了，请问是否可以改为参数可灵活配置， 并且可以设置检测次数？

顺便再提一个 SendLocalFile 有文件大小的限制， 如果发送大文件的话，可以用什么方式，有没有好的建议

**Comment by ldcsaa** [comment]
1. 必须1秒以上，否则对性能影响太大
2. 发送大文件用分块发送，然后组合存储

**Comment by anheiqq** [comment]
谢谢你的解答， 可能应用场景场景不一样，考虑的方向不一样， 我们的场景是一个局域网的数据通信，最多也就8个客户端， 而服务端是放在pc上给人使用的，连接后可以实时看到客户端的状态变化，是否掉线等，对检验掉线的实时性有些要求。所以这种场景下客户端是比较少的，即使减小检测周期，对性能也不会产生多大影响。如果参数可以设置的话，用户就可以根据不同场景和不同需求就行调整了，只要将各种利弊描述清楚即可。

可能这种应用场景比较少，如果不能设置，那我们就自己定义心跳包去实现吧。

再次感谢作者的贡献， 这个库我们使用一段时间了，非常的方便也很稳定， 谢谢

**Comment by ldcsaa** [comment]
Thanks~
