### ISSUE TITLE
CHttpsServer可以为每个CONNID绑定证书吗？

### ISSUE THREAD

**Issue by Endt4sk** [ldcsaa/HP-Socket#54]
CHttpsServer可以为每个CONNID绑定证书吗？

**Comment by ldcsaa** [comment]
服务端证书是相对于主机域名的，可以通过 AddSSLContext() 增加SNI主机证书。

**Comment by Endt4sk** [comment]
> 服务端证书是相对于主机域名的，可以通过 AddSSLContext() 增加SNI主机证书。

意思是根据请求的主机域名来使用不同的证书是吗？

**Comment by ldcsaa** [comment]
Yes
