### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by gczhcm** [ldcsaa/HP-Socket#57]
I use static lib of HP-SOCKET in linux.
`class Server : CTcpServerListener
{
private:
	CTcpServerPtr client;
}
void Server::ConnectConsole()
{
	std::string IP;
	unsigned short Port;
	std::tie(IP, Port) = this->ConsoleAddress;
	while (this->client->Start((LPCTSTR)IP.c_str(), Port ) == false)
	{
		printf("erro code %d,%s\n",this->client->GetLastError(), this->client->GetLastErrorDesc());
	}
}
 `
But error is "erro code 1,Illegal State", What should I do？

**Comment by ldcsaa** [comment]
`BOOL CTcpClient::CheckStarting()
{
	CSpinLock locallock(m_csState);

	if(m_enState == SS_STOPPED)
		m_enState = SS_STARTING;
	else
	{
		SetLastError(SE_ILLEGAL_STATE, __FUNCTION__, ERROR_INVALID_OPERATION);
		return FALSE;
	}

	return TRUE;
}`

if client->GetState() != SS_STOPPED, it would be return error SE_ILLEGAL_STATE.
that's to say you can reconnect only when client->GetState() == SS_STOPPED .

**Comment by gczhcm** [comment]
I find that client->GetState() is equal to 3,that is to say client->GetState() ==SS_STOPPED，but error is occur

**Comment by ldcsaa** [comment]
Could you post or upload load your complete code here ?
