### ISSUE TITLE
_test_hooks_arena_new_hook _test_hooks_libc_hook符号无法链接的问题

### ISSUE THREAD

**Issue by SoichiroGen** [ldcsaa/HP-Socket#58]
Visual C++2015 静态链接HPSocketLib4C.lib、HPSocketLib.lib提示外部符号无法链接的问题：
1>HPSocket4C_U.lib(arena.obj) : error LNK2001: 无法解析的外部符号 _test_hooks_arena_new_hook
1>HPSocket4C_U.lib(prof.obj) : error LNK2001: 无法解析的外部符号 _test_hooks_libc_hook

解决方案：
链接导入库去掉jmalloc.lib，重新编译HPSocketLib4C.lib、HPSocketLib.lib即可。

**Comment by ldcsaa** [comment]
Visual C++2015 工程配置问题，下个版本已解决。

**Comment by tyler2018** [comment]
遇到的同样的问题，如何解决？除了去掉jmalloc.lib这个方法。

**Comment by ldcsaa** [comment]
下载当前 master 版试试！

**Comment by ldcsaa** [comment]
5.5.1 已发布
