### ISSUE TITLE
are there plan to develop static lib for  hp-socket 

### ISSUE THREAD

**Issue by lionm117** [ldcsaa/HP-Socket#6]
**HP-SOCKET** is a awesome  network communication library  . 
but it only **provide two kind of methods** to call the package : 

>- **dll  calling **
>- **source  calling**

but in some of my project , especially some **simple project** , i prefer one file  could solve all the problem  instead of carrying a dll with the exe .  there is only one way to do that , using source code to do that .  which seems not convenient and unsafe as a lib *(  prevent from modification by accident )*

at the same time , some of former project used the static lib ,which could not  compatible with the HP-SOCKET. 

>  my question is : *are there any plan to develop a static lib for **hp-socket** * ?

**Comment by ldcsaa** [comment]
not yet ~
if you wonder static lib, you can convert  dll project to lib project ... good luck ~
