### ISSUE TITLE
C# UdpServer 只能接收到小于等于1432字节的数据

### ISSUE THREAD

**Issue by TYPEmber** [ldcsaa/HP-Socket#61]
我在.Net Framework 4.6.1的版本上调用的C#的接口，发现无法接收到长度大于1432字节的数据，请问这个应该如何解决呢？

**Comment by Ax2401** [comment]
> 我在.Net Framework 4.6.1的版本上调用的C#的接口，发现无法接收到长度大于1432字节的数据，请问这个应该如何解决呢？

HP默认设置的最大1432 , 可以自己调.

但是:
UDP如果是用于外网通信, 单次Send 最好别超1k, 否则大大增加丢包率.  (最稳妥的是500字节以下.)

 具体可以百度.

另外HP beta版本新增了可靠UDP组件, 可以试试.

**Comment by TYPEmber** [comment]
> 我在.Net Framework 4.6.1的版本上调用的C#的接口，发现无法接收到长度大于1432字节的数据，请问这个应该如何解决呢？
> 
> HP默认设置的最大1432 , 可以自己调.
> 但是:
> UDP如果是用于外网通信, 单次Send 最好别超1k, 否则大大增加丢包率.  (最稳妥的是500字节以下.)
> 具体可以百度.
> 另外HP beta版本新增了可靠UDP组件, 可以试试.

谢谢解答，我这边主要用于内网的通信，需要传输4052个字节的包。
请问这个在C#中是否有提供呢？

**Comment by Ricord** [comment]
> 
> 
> > 我在.Net Framework 4.6.1的版本上调用的C#的接口，发现无法接收到长度大于1432字节的数据，请问这个应该如何解决呢？
> > HP默认设置的最大1432 , 可以自己调.
> > 但是:
> > UDP如果是用于外网通信, 单次Send 最好别超1k, 否则大大增加丢包率.  (最稳妥的是500字节以下.)
> > 具体可以百度.
> > 另外HP beta版本新增了可靠UDP组件, 可以试试.
> 
> 谢谢解答，我这边主要用于内网的通信，需要传输4052个字节的包。
> 请问这个在C#中是否有提供呢？

可以分包处理

**Comment by ldcsaa** [comment]
1、不在意丢包的话可以直接 SetMaxDatagramSize() 增大长度
2、在意丢包的话可以改用 IUdpArqServer / IUdpArqClient

**Comment by ldcsaa** [comment]
> > 我在.Net Framework 4.6.1的版本上调用的C#的接口，发现无法接收到长度大于1432字节的数据，请问这个应该如何解决呢？
> > HP默认设置的最大1432 , 可以自己调.
> > 但是:
> > UDP如果是用于外网通信, 单次Send 最好别超1k, 否则大大增加丢包率.  (最稳妥的是500字节以下.)
> > 具体可以百度.
> > 另外HP beta版本新增了可靠UDP组件, 可以试试.
> 
> 谢谢解答，我这边主要用于内网的通信，需要传输4052个字节的包。
> 请问这个在C#中是否有提供呢？

1、不在意丢包的话可以直接 SetMaxDatagramSize() 增大长度
2、在意丢包的话可以改用 IUdpArqServer / IUdpArqClient
