### ISSUE TITLE
关于Linux下的c#问题

### ISSUE THREAD

**Issue by MOMOSUM** [ldcsaa/HP-Socket#65]
我目前用的HP版本是5.4.4，我引用Linux的libhpsocket4c.so文件，重新编译生成DLL文件。然后参考demo，写了一个tcpserver,一直出现“ErrorMsg:启动失败,错误码:Ok”。这个一直困扰了我很久，希望提供相关参考意见

**Comment by ldcsaa** [comment]
升级5.5.1吧。

**Comment by MOMOSUM** [comment]
嗯，我看了一下我Linux的字符为utf-8，使用非托管的方式调用so文件时，将字符设置为unicode。任然会出现“ErrorMsg:启动失败,错误码:Ok,错误信息:SUCCESS
	   at HttpServerDemo.MyHttpServer.Run(String bindAddress, UInt16 port) in C:\Users\10162\source\repos\testnewHP\testnewHP\MyHttpServer.cs:line 44”

**Comment by ldcsaa** [comment]
linux下是ansi，5.5.1版本统一为ansi了。

**Comment by mosakashaka** [comment]
我在5.1.1下也碰到这个问题，而且是通过Demo中的HPSocketCS库引用的libhpsocket4c.so，默认我看已经是ansi了。。。

**Comment by ldcsaa** [comment]
请下载现在的 master 分支试试 ！

**Comment by z514987467** [comment]
我用5.7.2出现了同样的问题，请问大神们怎么解决的
```
Error:
  An assembly specified in the application dependencies manifest (WebApi.deps.json) was not found:
    package: 'HPSocket.Net', version: '5.7.2'
    path: 'runtimes/linux-x64/native/libhpsocket4c.so'

```

**Comment by ldcsaa** [comment]
hp for .Net 已拆分为独立项目：https://github.com/int2e/HPSocket.Net
