### ISSUE TITLE
there should be a CMakeLists.txt

### ISSUE THREAD

**Issue by RPG3D** [ldcsaa/HP-Socket#67]

**Comment by ldcsaa** [comment]
use compile.sh

**Comment by Ax2401** [comment]
> use compile.sh and install.sh

我觉得应该支持cmake  这样看上去比较国际化

**Comment by ldcsaa** [comment]
if have time, will  support cmake .

**Comment by leasual** [comment]
@RPG3D @Ax2401 编译HP-Socket的CMakeLists.txt  `cmake_minimum_required(VERSION 3.4.1)

set(CMAKE_VERBOSE_MAKEFILE on)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_library(hpsocket
        SHARED
        src/HPSocket.cpp
        src/HPSocket-SSL.cpp
        src/HttpAgent.cpp
        src/HttpClient.cpp
        src/HttpCookie.cpp
        src/HttpHelper.cpp
        src/HttpServer.cpp
        src/HPThreadPool.cpp
        src/ArqHelper.cpp
        src/MiscHelper.cpp
        src/SocketHelper.cpp
        src/SSLAgent.cpp
        src/SSLClient.cpp
        src/SSLHelper.cpp
        src/SSLServer.cpp
        src/TcpAgent.cpp
        src/TcpClient.cpp
        src/TcpPackAgent.cpp
        src/TcpPackClient.cpp
        src/TcpPackServer.cpp
        src/TcpPullAgent.cpp
        src/TcpPullClient.cpp
        src/TcpPullServer.cpp
        src/TcpServer.cpp
        src/UdpCast.cpp
        src/UdpClient.cpp
        src/UdpServer.cpp
        src/UdpArqClient.cpp
        src/UdpArqServer.cpp
        src/common/BufferPool.cpp
        src/common/Event.cpp
        src/common/FuncHelper.cpp
        src/common/IODispatcher.cpp
        src/common/PollHelper.cpp
        src/common/RWLock.cpp
        src/common/FileHelper.cpp
        src/common/SysHelper.cpp
        src/common/http/http_parser.c
        src/common/kcp/ikcp.c
        src/common/crypto/Crypto.cpp
        src/common/Thread.cpp)

#add crypto
add_library(crypto STATIC IMPORTED)
set_target_properties(crypto PROPERTIES IMPORTED_LOCATION
        ${CMAKE_SOURCE_DIR}/openssl/${ANDROID_ABI}/lib/libcrypto.a)
#add ssl
add_library(ssl STATIC IMPORTED)
set_target_properties(ssl PROPERTIES IMPORTED_LOCATION
        ${CMAKE_SOURCE_DIR}/openssl/${ANDROID_ABI}/lib/libssl.a)

add_library(charset STATIC IMPORTED)
set_target_properties(charset PROPERTIES IMPORTED_LOCATION
        ${CMAKE_SOURCE_DIR}/openssl/${ANDROID_ABI}/lib/libcharset.a)

add_library(iconv STATIC IMPORTED)
set_target_properties(iconv PROPERTIES IMPORTED_LOCATION
        ${CMAKE_SOURCE_DIR}/openssl/${ANDROID_ABI}/lib/libiconv.a)

include_directories(${CMAKE_SOURCE_DIR}/openssl/${ANDROID_ABI}/include)

target_link_libraries(hpsocket ssl crypto charset iconv)

# copy out the lib binary and remove generated files
set(distribution_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../../../distribution)
set_target_properties(hpsocket
        PROPERTIES
        LIBRARY_OUTPUT_DIRECTORY
        "${distribution_DIR}/hpsocket/lib/${ANDROID_ABI}")

## config support ssl -D_NEED_SSL
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DNDEBUG -D_NEED_SSL -D_NEED_HTTP -D_ZLIB_DISABLED -D_ICONV_DISABLED")

add_custom_command(TARGET hpsocket POST_BUILD
        COMMAND "${CMAKE_COMMAND}" -E copy_directory "${CMAKE_CURRENT_SOURCE_DIR}/include/"
        "${distribution_DIR}/hpsocket/include/"
        COMMENT "Copying gperf to output directory")`
