### ISSUE TITLE
why depending on MFC/ALT on Windows?

### ISSUE THREAD

**Issue by RPG3D** [ldcsaa/HP-Socket#69]

**Comment by RPG3D** [comment]
the demo may depend on MFC/ALT. but library should not.

**Comment by ldcsaa** [comment]
yes，library does not ！

**Comment by RPG3D** [comment]
library ref common, common ref mfc/alt

**Comment by ldcsaa** [comment]
only static ref atl，the application which uses hp dll does not need to ref atl。
