### ISSUE TITLE
是否支持TLS

### ISSUE THREAD

**Issue by bigwatercar** [ldcsaa/HP-Socket#71]
能支持TLS吗

**Comment by SunLiangcan** [comment]
可以支持，你也在用hp?




------------------ 原始邮件 ------------------
发件人: "bigwatercar"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 上午10:34
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ldcsaa/HP-Socket] 是否支持TLS (#71)




能支持TLS吗

**Comment by bigwatercar** [comment]
还在调研

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: SunLiangcan <notifications@github.com>
发送时间: Monday, May 20, 2019 10:35:33 AM
收件人: ldcsaa/HP-Socket
抄送: bigwatercar; Author
主题: Re: [ldcsaa/HP-Socket] 是否支持TLS (#71)

可以支持，你也在用hp?




------------------ 原始邮件 ------------------
发件人: "bigwatercar"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 上午10:34
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ldcsaa/HP-Socket] 是否支持TLS (#71)




能支持TLS吗

―
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by ldcsaa** [comment]
支持~ 请放心使用！
