### ISSUE TITLE
可以支持p2p吗

### ISSUE THREAD

**Issue by xcy2030** [ldcsaa/HP-Socket#72]
UdpArqClient 和   和 UdpArqClient   可以收发数据吗？

**Comment by ldcsaa** [comment]
HP-Socket 的 UDP 基于 C/S 结构，不支持 C2C

**Comment by xcy2030** [comment]
Udp的可靠传输  server 和client 里的  SendPackets  有问题  
CBufferPtr sndBuffer  你可以确认下 ，

**Comment by ldcsaa** [comment]
未发现你说的问题，可以进群详细描述问题。
