### ISSUE TITLE
tcp server receiver

### ISSUE THREAD

**Issue by gczhcm** [ldcsaa/HP-Socket#73]
![YZ40 BAB3Q%G9JTO$N))1S9](https://user-images.githubusercontent.com/18482740/58612819-76478b80-82e6-11e9-8dba-ec2a042be1b0.png)
The IP of TCP server is 192.168.10.103, and the client's IP is 192.168.10.200. When the client sends PSH packets, TCP retransmission and TCP DUP will appear intermittently. How should I set TCP server in hp-socket to solve this problem?

**Comment by gczhcm** [comment]
and how to get SOCKET fd according to CONNID dwConnID？

**Comment by Ax2401** [comment]
1. DUP ACK  和重传一般与应用层关系不大,  检查下内网环境.  (可以在内网搭建FTP / 或SMB共享, 然后传送文件, 观察是否也有重传和dup ACK)

2. Server端: 
    在 OnPrepareListen回调的soListen参数中得到 Server的socket句柄;
    在OnAccept中可以得到客户端的socket句柄.

    Client端:
    在OnPrepareConnect回调参数中可以得到客户端的socket句柄.

**Comment by ldcsaa** [comment]
Server:  listen socket - OnPrepareListen(), trans socket - OnAccept()
Client / Agent: OnPrepareConnect()
