### ISSUE TITLE
请问 CRingCache2 中的 m_px变量的作用？

### ISSUE THREAD

**Issue by zuowanbushiwo** [ldcsaa/HP-Socket#74]
没看明白 m_px 的作用，应为从代码上看 m_px 在初始的时候被赋值为0 后，就一直没有变化了，没有被修改的地方，用vs 跟踪这段内存也是显示一直为0。
而且也不理解 CRingCache2 和 CRingCache 有什么不一样的？从成员变量看 CRingCache2 多了一个 m_px 变量，当这个一直为0时，CRingCache2 和  CRingCache 处理 index 的方式就一样了,那这两个类所有的函数的功能就一样了，不知道理解对不对？
谢谢！

**Comment by ldcsaa** [comment]
m_px 1 byte（0~255），用于放大 ring cache 索引号。virtualIndex = realIndex + (ringSize * m_px)

**Comment by zuowanbushiwo** [comment]
是啊，我理解也是这样，虽然不太懂意义，只知道这个是索引index 的映射转换。但是关键m_px 值在代码里面不是一直都是0吗？没看到有被赋值的地方？905行的这句话 ++(*(m_px + dwRealIndex)); 对程序有影响吗？我去掉后再调试程序也是正常的。

**Comment by ldcsaa** [comment]
这句话就是增加 m_px数值的，不能删除。
