### ISSUE TITLE
HPSocket4J

### ISSUE THREAD

**Issue by opjkjava** [ldcsaa/HP-Socket#77]
传说已经支持 java调用。但是找不到 java依赖jar。请问的确支持么？

**Comment by mapleo** [comment]
可以支持的   要jna,；如是做成jni那当然更好




------------------ 原始邮件 ------------------
发件人: "opjkjava"<notifications@github.com>;
发送时间: 2019年6月19日(星期三) 中午12:09
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ldcsaa/HP-Socket] HPSocket4J (#77)




传说已经支持 java调用。但是找不到 java依赖jar。请问的确支持么？

**Comment by mapleo** [comment]
> 传说已经支持java调用。但是找到不到java依赖jar。请问的确支持么？

我个人对java略知一点；jna的例程网上有的；能跑，但也有一些错误；如有需要我可以找找发mail给您，版本是旧版的

**Comment by dlhxd** [comment]
jni了解一下，并不需要其他包支持------------------ 原始邮件 ------------------
发件人: "mapleo"<notifications@github.com>
发送时间: 2019年6月19日(星期三) 晚上6:22
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [ldcsaa/HP-Socket] HPSocket4J (#77)


 
传说已经支持java调用。但是找到不到java依赖jar。请问的确支持么？
  
我个人对java略知一点；jna的例程网上有的；能跑，但也有一些错误；如有需要我可以找找发mail给您，版本是旧版的
 
&mdash;

**Comment by ldcsaa** [comment]
3.2.1版本之后就移除了java sdk，还没有计划重新加上。要用的话要自己用jni/jna支持。
