### ISSUE TITLE
.net core/linux下使用问题，HP_Server_HasStarted状态错误

### ISSUE THREAD

**Issue by mosakashaka** [ldcsaa/HP-Socket#78]
原本打算在Linux环境，.netcore下使用，但是发现Server无法启动。错误和[关于Linux下的c#问题](https://github.com/ldcsaa/HP-Socket/issues/65)这个问题中描述一样。
但是CharSet已经设置成了ANSI（工程自带的HPSocketCS工程就是用的ANSI）。

稍微看了一下代码，发现是当Server还未启动时，`HP_Server_HasStarted`就会返回`True`，导致`HP_Server_Start`不会被调用。

然后我单独测试HP_Server_HasStarted这个接口，发现的确有这个问题。我的测试代码是`https://gitee.com/mosakashaka/HPDemo.git`这个工程，可以直接拉取下来`dotnet build`就能编译运行。关键的代码只有这几句：

```c#
            IntPtr pListener = Sdk.Create_HP_TcpServerListener();
            if (pListener == IntPtr.Zero)
            {
                Console.WriteLine("Create_HP_TcpServerListener Failed");
                return;
            }

            IntPtr pServer = Sdk.Create_HP_TcpServer(pListener);
            if (pServer == IntPtr.Zero)
            {
                Console.WriteLine("Create_HP_TcpServer Failed");
                return;
            }

            Console.WriteLine($"Server start state before start:[{Sdk.HP_Server_HasStarted(pServer)}]");
```

而最后一句的打印，HP_Server_HasStarted会打印`True`。

库我用的是5.5.2自带的`Linux\lib\hpsocket4c\x64\libhpsocket4c.so`。

另一个奇怪的地方在于，如果我用DEBUG版本的库`libhpsocket4c_d.so`运行，就没有这个问题（我也自己在linux下编译了这个库，是同样的结果）。。

不知道是否我使用的问题，谢谢

**Comment by withsalt** [comment]
我也遇到同样的问题

**Comment by ldcsaa** [comment]
暂时先修改代码，吧HasStart判断去掉，看看windows版有没有问题。

**Comment by mosakashaka** [comment]
> 暂时先修改代码，吧HasStart判断去掉，看看windows版有没有问题。

之前一直用win版，同样的代码，没有问题。

想切换成linux版本发现的这个问题，去掉HasStart判断server启动没有问题，不过还没有做更多的功能测试。

**Comment by ldcsaa** [comment]
这个问题我会跟进

**Comment by mosakashaka** [comment]
谢谢

**Comment by ldcsaa** [comment]
有可能 .net core 的 bug

**Comment by mosakashaka** [comment]
> 有可能 .net core 的 bug

进一步看了一下，原因应该是c++的bool为1个字节，而c# bool为四个字节，参考了SO的[这个问题](https://stackoverflow.com/questions/4608876/c-sharp-dllimport-with-c-boolean-function-not-returning-correctly)。

windows下小端，所以没问题。linux下大端，只会取到高位的0。

debug下以及添加打印后可以正常没有想明白原因。。。c++下可以正常引用因为不需要marshel。

我将c#函数引用定义修改为
```c#
[DllImport(HPSOCKET_DLL_PATH, CharSet = CharSet.Ansi, SetLastError = true)]
[return:MarshalAs(UnmanagedType.I1)]
public static extern bool HP_Server_HasStarted(IntPtr pServer);
```

就能正确获取到结果。
具体功能还需要更多测试，不过看起来所有的BOOL类型返回值都要增加这个属性设置

**Comment by ldcsaa** [comment]
目前的 common/GlobalDef.h 定义：
-----------------------------------------

typedef bool    BOOL;
#define TRUE   true
#define FALSE  false


你修改一下源码重新编译一下试试：
-----------------------------------------

1、 common/GlobalDef.h 

typedef int    BOOL;
#define TRUE   1
#define FALSE  0

2、common/CriSec.h (72行)

atomic_bool 改为 atomic_int

**Comment by mosakashaka** [comment]
> CriSec.h

初步试了一下，修改后可以使用（不加`[return:MarshalAs(UnmanagedType.I1)]`)。

另外代码有两个`GlobalDef.h`，分别在`Linux\include\hpsocket\common`和`Linux\src\common`，不知道哪个有影响，我两个都改了。

**Comment by ldcsaa** [comment]
请下载现在的 master 分支试试 ！

**Comment by mosakashaka** [comment]
> 请下载现在的 master 分支试试 ！

谢谢，我试一下

**Comment by mosakashaka** [comment]
20190701版本问题解决。
