### ISSUE TITLE
CUdpArqServer 会出现卡死的现象

### ISSUE THREAD

**Issue by xcy2030** [ldcsaa/HP-Socket#79]
使用udpArqClient 向 udpArpServer 发送数据  过一会 会出现卡死的现象 ， 再启动一个新的客户端给UdpArqServer 发送数据   ，UdpArqServer还是收不到数据， 监听端口还在， 请问这个问题可以帮忙看下吗

**Comment by ldcsaa** [comment]
因为你onreceive一直不返回，把io线程占满了。

**Comment by xcy2030** [comment]
我还是不太明白  ，这个框架 我只是大致的看了下  你可以讲下怎么解决这个问题吗  谢谢了。

**Comment by ldcsaa** [comment]
多看看开发文档和demo
