### ISSUE TITLE
是否支持编译给iOS项目使用

### ISSUE THREAD

**Issue by Vienta** [ldcsaa/HP-Socket#8]
你好
非常棒的一个项目！最近刚使用c++，这个库能否编译给iOS项目使用？

期望回复
Vienta

**Comment by 58753101** [comment]
支持的，这不是我的，我也是从其他地方弄的，你可以到http://www.oschina.net/news/50934/hp-socket-3-2-1-rc1 这里看看

**Comment by Vienta** [comment]
你好
我尝试着弄了下，最后没有编译成功，里面有mfc等，文档上也没有提到支持mac平台，楼主在编译这个上面能否指点指点呢？

Vienta

**Comment by ldcsaa** [comment]
目前不支持~

**Comment by adanac** [comment]
期待新的版本

**Comment by lion117** [comment]
目前HPSOCKET 仅支持windows 平台, linux , mac 均不支持. HPSOCKET 采用了大量的windows 平台的技术做底层, 解耦工作强度较大, 毕竟是开源软件, 修复bug什么**怪兽**比较倾力为之, 但是拓展到其他平台, 没有众人之力, 还是够呛的

**Comment by ldcsaa** [comment]
下个版本先支持Linux~
