### ISSUE TITLE
Release of additional data about connections

### ISSUE THREAD

**Issue by gczhcm** [ldcsaa/HP-Socket#80]
I use SetConnectionExtra/GetConnectionExtra follow these steps
1）Bind the Connection ID to the Application Layer Data by SetConnectionExtra(dwConnID, pExtra) in OnAccept() / OnConnect() 
2) Get Application Layer Data bound to Connection ID by GetConnectionExtra(dwConnID, ppExtra) in OnReceive() / OnSend()
3) Unbound Connection ID and Application Layer Data to Clear Application Layer Data and release resources in  OnClose().
And now, I have some question.
1) How to  unbound Connection ID and Application Layer Data, use SetConnectionExtra()？
such as SetConnectionExtra(dwConnID,nullptr).
2) How should I release resources when OnReceive and OnClose coincide  ?
````C++
class ConnectInfo
{
  private:
    std::mutex ConnectMutex;
    bool doing; //indicate if use this ConnectInfo
    .......
}
EnHandleResult MyListenServer::OnAccept(ITcpServer *pSender, CONNID dwConnID, UINT_PTR soClient)
{
    NOTICE("Receiving terminal station connection request");
    ConnectInfo *info=new ConnectInfo();
    bool flag=this->server->SetConnectionExtra(dwConnID,info);
    if(!flag)
    {
        char text[64]={0};
        sprintf(text,"Set ConnectInfo fail, dwConnID:%d",dwConnID);
        FATAL(text);
        delete info;
        info=nullptr;
    }
    return EnHandleResult::HR_OK;
}

EnHandleResult MyListenServer::OnReceive(ITcpServer* pSender, CONNID dwConnID, const BYTE* pData, int iLength)
{
    ConnectInfo *info;
    if(this->server->GetConnectionExtra(dwConnID,(void **)(&info))&&info)//1 get data 
    {
       info->ConnectMutex.lock();
        info->doing=true;
        info->ConnectMutex.unlock();
         .......
       info->ConnectMutex.lock();
        info->doing=false;
        info->ConnectMutex.unlock();
    }
}


EnHandleResult MyListenServer::OnClose(ITcpServer* pSender, CONNID dwConnID, EnSocketOperation enOperation, int iErrorCode)
{
    ConnectInfo *info;
    if(this->server->GetConnectionExtra(dwConnID,(void **)(&info))&&info)
    {
        this->server->SetConnectionExtra(dwConnID,nullptr);
       while(1)
       {
           info->ConnectMutex.lock();
           if(info->doing)
            {
                  info->ConnectMutex.unlock();
		  usleep(1000 * 30);
		  continue;
            }
           info->ConnectMutex.unlock();
           delete info;
           info=nullptr;
           break;
       }
       
         .......
     
    }
    return EnHandleResult::HR_OK;
}
````
And then does that happen? OnReceive() has run  ' if(this->server->GetConnectionExtra(dwConnID,(void **)(&info))&&info)' , but  don't run ‘ info->ConnectMutex.lock();  info->doing=true; info->ConnectMutex.unlock();’ .   And OnClose() finds info->doing is false，so it will delete info. This can lead to segmentation fault in   'info->ConnectMutex.lock();' of OnReceive().
I don't know if this will happen, and how I should release resources.

**Comment by ldcsaa** [comment]
1. OnReceive / OnClose events are thread-safe event, that means OnReceive / OnClose would not be triggered at the same time.
2. OnSend event is not thread-safe by default, that means  OnReceive / OnClose would be triggered at the same time with OnSend. But you can change SetOnSendSyncPolicy(EnOnSendSyncPolicy) to make it thread-safe.

**Comment by gczhcm** [comment]
thx，but SetOnSendSyncPolicy is invalid to linux，so  OnSend event is not thread-safe  for me.

**Comment by ldcsaa** [comment]
Both Linux & Windows support SetOnSendSyncPolicy()
