### ISSUE TITLE
跨平台定义需要改进

### ISSUE THREAD

**Issue by WenchaoXia** [ldcsaa/HP-Socket#82]
clang交叉编译Linux x86_64版本时发现以下问题：
1 GlobalDef.h需要大幅简化，内部使用的定义隐藏起来以免冲突。
2 不要在API里使用TCHAR，因为在Linux里这是工程定义的而不是平台定义的，有些工程出于code size考虑用的是utf16，建议替换TCHAR->HPSOCKET_TCHAR
3 SSIZE_T使用指针类型大小，或隐藏到内部不要放到外部引用头文件里。
4 GlobalDef.h里去掉_UNICODE的使用，这里容易引起冲突以及用户误会，其他的用户工程很可能定义了这个宏，实际HPSOCKET里_UNICODE没定义，我试了下_UNICODE定义后libHPSOCKET编译失败。

**Comment by ldcsaa** [comment]
不打算修改，亲~~
