### ISSUE TITLE
发送大量数据流导致程序内存不断在上升

### ISSUE THREAD

**Issue by huangmin007** [ldcsaa/HP-Socket#83]
如题，开发语言C++
发送的是实时数据流，持续发送，调用 HP_Client_Send(pClient, buffer, size) 后内存不断上升，发送后有 clear buffer，注释掉 HP_Client_Send(pClient, buffer, size) 后就好了，

**Comment by Ax2401** [comment]
HP所有组件的Send都是异步的,  如果上传带宽不够,  组件会"缓存"要发送的数据.   如果无节制的调用Send , 内存必然无限增长.   要自己做好流控. 

GetPendingDataLength()接口可以知道当前客户端有多少数据正在缓存中,  尚未发送出去.

**Comment by huangmin007** [comment]
我用的是127.0.0.1的ip，本机测试，每秒在7-8M的数据左右，应该不存在带宽不够，呀
如果控流，就是要等缓存中的数据低于多少后，在Send，那就会有延时...

**Comment by Ax2401** [comment]
每秒7 - 8M 一般不会有问题, 检查自己其他逻辑, 比如接收端是否阻塞了HP的工作线程(回调长时间不返回).     

延时问题:
如果你上传带宽是4M, 你的发送速率是每秒400M, 无论你控不控, 对端都延时.

**Comment by Ax2401** [comment]
限流, 不是说无条件一律限流.

**Comment by huangmin007** [comment]
谢谢!!
