### ISSUE TITLE
need osx supported

### ISSUE THREAD

**Issue by liesauer** [ldcsaa/HP-Socket#87]
我尝试了在osx下编译，在解决了sh脚本的系统、位数检测问题后（修改`env.sh`文件的`check_platform`和`parse_envs`），尝试编译不通过。
https://github.com/ldcsaa/HP-Socket/blob/ae089f72e170de22e4ae9c7c0452c7b7359f0b4a/Linux/script/env.sh#L60-L105
改成
```shell
check_platform()
{
	PLATFORM=
	
	# if [ "$1" == "x86_64" ]; then
		PLATFORM="x64"
	# elif [[ "$1" == "i686" || "$1" == "i386" ]]; then
	# 	PLATFORM="x86"
	# elif [[ "$1" =~ "arm" ]]; then
	# 	PLATFORM="ARM"
	# fi
}

parse_envs()
{
	local OS_NAME=$(uname -s | tr "[A-Z]" "[a-z]")

	# 注释掉，以便在osx下通过
	# if [ "$OS_NAME" != "linux" ]; then
	# 	printf "OS Platform not supported: %s\n" $OS_NAME
	# 	exit 1
	# fi
	
	# osx下arch和uname -p好像有问题？实际是x86_64，检测是i386
	# check_platform直接写死x64
	check_platform "$(arch | tr "[A-Z]" "[a-z]")"
	
	if [ -z $PLATFORM ]; then
	
		check_platform "$(uname -p | tr "[A-Z]" "[a-z]")"
		
		if [ -z $PLATFORM ]; then
			printf "Can not determine Arch Platform\n"
			exit 1
		fi
	fi
	
	if [ ! -f $HP_DEF_FILE_PATH ]; then
		printf "HP-Socket version file not exists: '%s'\n" $HP_DEF_FILE_PATH
		exit 1
	fi

	VER_MAJOR=$(parse_version "$VER_MAJOR_MICRO")
	VER_MINOR=$(parse_version "$VER_MINOR_MICRO")
	VER_REVISE=$(parse_version "$VER_REVISE_MICRO")
	VER_BUILD=$(parse_version "$VER_BUILD_MICRO")
	
	reset_env_args
}
```

在编译时遇到error，使用了linux专有的header
```
src/common/SysHelper.h:33:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>
         ^~~~~~~~~~~~~~~
3 warnings and 1 error generated.
```
查阅得知
```
From man sysinfo:

Code:
SYSINFO(2)                 Linux Programmer's Manual                SYSINFO(2)



NAME
       sysinfo - returns information on overall system statistics

SYNOPSIS
       #include <sys/sysinfo.h>

       int sysinfo(struct sysinfo *info);

DESCRIPTION
...

CONFORMING TO
       This function is Linux-specific, and should not  be  used  in  programs
       intended to be portable.

This header and its contents are linux-specific. You're not going to be able to make it compile without rewriting or ripping out whatever parts use it. (The programming forum here may be able to help you with that.) If you're lucky, it's not actually using sysinfo and you can comment out the errant #include.
```

**Comment by ldcsaa** [comment]
之前有人做过移植，请参考：https://gitee.com/xin_chong/HP-Socket-for-macOS

**Comment by liesauer** [comment]
> 之前有人做过移植，请参考：https://gitee.com/xin_chong/HP-Socket-for-macOS

好的，谢谢，另外想问下官方有做这个打算吗？

**Comment by liesauer** [comment]
我尝试结合HPSocketCS用了下，貌似缺了很多组件
```
ErrorMsg:Unable to find an entry point named 'Create_HP_HttpServerListener' in shared library 'hpsocket4c'.
	   at HPSocketCS.HttpSdk.Create_HP_HttpServerListener()
   at HPSocketCS.SSLHttpServer.CreateListener() in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/HPSocketCS/SSLHttpServer.cs:line 88
   at HPSocketCS.TcpServer..ctor() in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/HPSocketCS/TcpServer.cs:line 80
   at HPSocketCS.HttpServer..ctor()
   at HPSocketCS.SSLHttpServer..ctor(SSLVerifyMode verifyModel, String pemCertFile, String pemKeyFile, String keyPasswod, String caPemCertFileOrPath, SNIServerNameCallback sniServerNameCallback) in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/HPSocketCS/SSLHttpServer.cs:line 69
   at HPSocketCS.HttpsServer..ctor(SSLVerifyMode verifyModel, String pemCertFile, String pemKeyFile, String keyPasswod, String caPemCertFileOrPath, SNIServerNameCallback sniServerNameCallback) in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/HPSocketCS/SSLHttpServer.cs:line 17
   at HttpServerDemo.MyHttpsServer.Run(String bindAddress, UInt16 port) in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/myServer/MyHttpsServer.cs:line 15
   at HttpServerDemo.Program.Main(String[] args) in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/myServer/Program.cs:line 34
```

**Comment by ldcsaa** [comment]
> > 之前有人做过移植，请参考：https://gitee.com/xin_chong/HP-Socket-for-macOS
> 
> 好的，谢谢，另外想问下官方有做这个打算吗？

目前还没有

**Comment by ldcsaa** [comment]
> 我尝试结合HPSocketCS用了下，貌似缺了很多组件
> 
> ```
> ErrorMsg:Unable to find an entry point named 'Create_HP_HttpServerListener' in shared library 'hpsocket4c'.
> 	   at HPSocketCS.HttpSdk.Create_HP_HttpServerListener()
>    at HPSocketCS.SSLHttpServer.CreateListener() in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/HPSocketCS/SSLHttpServer.cs:line 88
>    at HPSocketCS.TcpServer..ctor() in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/HPSocketCS/TcpServer.cs:line 80
>    at HPSocketCS.HttpServer..ctor()
>    at HPSocketCS.SSLHttpServer..ctor(SSLVerifyMode verifyModel, String pemCertFile, String pemKeyFile, String keyPasswod, String caPemCertFileOrPath, SNIServerNameCallback sniServerNameCallback) in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/HPSocketCS/SSLHttpServer.cs:line 69
>    at HPSocketCS.HttpsServer..ctor(SSLVerifyMode verifyModel, String pemCertFile, String pemKeyFile, String keyPasswod, String caPemCertFileOrPath, SNIServerNameCallback sniServerNameCallback) in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/HPSocketCS/SSLHttpServer.cs:line 17
>    at HttpServerDemo.MyHttpsServer.Run(String bindAddress, UInt16 port) in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/myServer/MyHttpsServer.cs:line 15
>    at HttpServerDemo.Program.Main(String[] args) in /Users/imac/Projects/HP-Socket/Windows/Other Languages/C#/HPSocketCS/myServer/Program.cs:line 34
> ```

下载最新5.5.3，并参考demo

**Comment by liesauer** [comment]
目前`HPSocketCS `和`HP-Socket-for-macOS`两个项目都是最新的，我在`HP-Socket-for-macOS`全局搜索了`Create_HP_HttpServerListener `这个函数，确实是不存在的

**Comment by Aisiok** [comment]
> 目前`HPSocketCS `和`HP-Socket-for-macOS`两个项目都是最新的，我在`HP-Socket-for-macOS`全局搜索了`Create_HP_HttpServerListener `这个函数，确实是不存在的

不好意思，这个问题会尽快修复。
在移植过程中漏掉了相关函数。
: )

**Comment by liesauer** [comment]
> > 目前`HPSocketCS `和`HP-Socket-for-macOS`两个项目都是最新的，我在`HP-Socket-for-macOS`全局搜索了`Create_HP_HttpServerListener `这个函数，确实是不存在的
> 
> 不好意思，这个问题会尽快修复。
> 在移植过程中漏掉了相关函数。
> : )

好，麻烦了🙏

**Comment by Aisiok** [comment]
> > > 目前`HPSocketCS `和`HP-Socket-for-macOS`两个项目都是最新的，我在`HP-Socket-for-macOS`全局搜索了`Create_HP_HttpServerListener `这个函数，确实是不存在的
> > 
> > 
> > 不好意思，这个问题会尽快修复。
> > 在移植过程中漏掉了相关函数。
> > : )
> 
> 好，麻烦了🙏

你好，我已经在第三方项目上更新并说明了如何使用4C接口，请及时查看。
hpsocket本身源码提供了4C、4CXX的接口，原本只是去除了相关4C接口减少移植时问题复杂度，带来不便不好意思。:(
现在的解决方案为临时的，当hpsocket更新5.6.x release版时第三方for macOS也会进行更全面的移植维护工作。

：>
祝工作生活愉快

**Comment by liesauer** [comment]
@Aisiok 感谢！目前已成功编译4c，但编译中有点小坑自己填了，已在原repo提出！

**Comment by ldcsaa** [comment]
https://gitee.com/xin_chong/HP-Socket-for-macOS

**Comment by liesauer** [comment]
鉴于已有实现，关闭此issue
https://gitee.com/xin_chong/HP-Socket-for-macOS
https://github.com/int2e/HPSocket.Net
