### ISSUE TITLE
调用send后，返回false，但是GetLastError返回的是0

### ISSUE THREAD

**Issue by ugenehan** [ldcsaa/HP-Socket#88]
CTcpClientPtr声明的一个client，调用client->Send()后，有时返回false，有时返回true，通过GetLastError()获取失败值时，都是0或success。Send有时会成功，有时会失败。

**Comment by mnt-github** [comment]
Hi, @ugenehan.
Did you solved this problem?
This issue is being raised with me.
Please, help me.
