### ISSUE TITLE
[建议]建议把编译好的demo或者文件以releases附件的形式上传

### ISSUE THREAD

**Issue by liesauer** [ldcsaa/HP-Socket#89]
好处就是，不会随着版本的更新，git库里记录堆积了一大堆文件，导致git库异常庞大，在下载demo的时候可以自由选择平台对应的文件，不需要说自己去拉取代码库（git庞大得拉半天）或者是一个一个文件点下载（demo分了文件夹或者分了不同文件需要一个一个下载），放在releases那里的话，打包成zip就会好很多。可以参考下我自己的一个库的做法，https://github.com/nulastudio/NULASpider/releases

**Comment by ldcsaa** [comment]
不知道如何分开打包呀
