### ISSUE TITLE
QT的支持

### ISSUE THREAD

**Issue by qhs1573** [ldcsaa/HP-Socket#91]
作者你好，感谢你提供HPSocket框架，我想在QT下使用当我把dll放进去按照Demo编译是有些语法不支持编译不过去，以后能提供QT支持的Api吗？谢谢

**Comment by ldcsaa** [comment]
QT一直都兼容的，可以进群问问那些整合过QT的人。

**Comment by qhs1573** [comment]
好的  明白了，非常感谢！

**Comment by yanche521** [comment]
在Qt下一下监听失败，是怎么回事：
1.写了一个类继承自CUDPServerListener，实现了对应的虚函数
2.写了一个类，初始化的时候，创建了CUDPArqClientPtr:
CUDPArqClientPtr * m_ptr = new CUDPArqClientPtr(&m_listerner);
然后调用 bool _ret = m_prt->Get()->Start("0.0.0.0", 20211);
结果，_ret变量返回的总是false，不明白怎么解决，查看了一下错误码是3，就是创建SOCKET失败。

不知道问题出在那哪里了？

**Comment by akjay** [comment]
应该是字符集的问题 Unicode和多字节字符集
