### ISSUE TITLE
用LoadLibrary加载HPSocket_UD.dll再调用FreeLibrary无法卸载

### ISSUE THREAD

**Issue by sulijiang** [ldcsaa/HP-Socket#93]
HINSTANCE hinstLib;
hinstLib = LoadLibrary(TEXT("HPSocket_UD.dll"));
FreeLibrary(hinstLib);
加载后中间没有任何操作无法卸载 Win7

**Comment by ldcsaa** [comment]
1、确定加载是否成功。
2、确定卸载是否成功。如果失败错误码是什么？
3、确定是否加载正确的发行版（带_U还是不带_U的版本）

**Comment by ldcsaa** [comment]
1、确定加载是否成功。如果失败错误码是什么？
2、确定卸载是否成功。如果失败错误码是什么？
3、确定是否加载正确的发行版（带_U还是不带_U的版本）

**Comment by sulijiang** [comment]
> 1，确定加载是否成功。如果失败错误代码是什么？
> 2，确定重新加载是否成功。如果失败错误代码是什么？
> 3，确定是否加载正确的发行版（带_U还是不带_U的版本）

加载和卸载都成功了
![image](https://user-images.githubusercontent.com/20531855/69300303-c11ade00-0c4d-11ea-8f22-7964bdedac54.png)

**Comment by ldcsaa** [comment]
FreeLibrary() 返回TRUE，说明引用计数递减成功，如果dll还在说明还有其它地方引用；如果返回FALSE，检查GetLastError()。

**Comment by sulijiang** [comment]
> FreeLibrary() 返回TRUE，说明引用计数递减成功，如果dll还在说明还有其它地方引用；如果返回FALSE，检查GetLastError()。

我试过多调用几次Freelibrary都没效果，我尝试了新建一个控制台项目，里面只有调用了LoadLibrary然后调用FreeLibrary，也是无法卸载，不知道还有什么地方引用的。

**Comment by ldcsaa** [comment]
你是不是通过在工程中加入 .lib 的方式静态引入了动态库？

**Comment by ldcsaa** [comment]
已解决，将于5.7.1版本修复

**Comment by sulijiang** [comment]
> @sulijiang
> 已确认是OpenSSL的静态库导致DLL不能卸载，此问题要等的OpenSSL 1.1.1e版本发布后才能修复。
> 如果你没用到SSL功能可以在HPTypeDef.h中排除SSL（＃定义_SSL_DISABLED）重新编译DLL。

好的谢谢了

**Comment by sulijiang** [comment]
close
