### ISSUE TITLE
udp握手阶段的onsend为什么回调给用户

### ISSUE THREAD

**Issue by squirrelfish** [ldcsaa/HP-Socket#94]

**Comment by ldcsaa** [comment]
ArqUdp？
触发OnSend不是什么问题。

**Comment by squirrelfish** [comment]
握手成功前的OnReceive没有回调给用户，OnSend却回调给用户，这里存在逻辑不一致。要么像TCP一样握手成功前什么都不回调给用户（我建议这种，消除协议差异），要么把握手成功前的OnReceive也回调给用户。

**Comment by ldcsaa** [comment]
这样挺好不计划改。
1、可以看见握手的部分过程
2、OnSend可以做流量统计
