### ISSUE TITLE
编译后的dll需要用到bcrypt.dll?

### ISSUE THREAD

**Issue by ugenehan** [ldcsaa/HP-Socket#95]
在XP下用vs2010编译，编译后的DLL需要bcrypt.dll？

**Comment by ldcsaa** [comment]
请更新至最新版

**Comment by ugenehan** [comment]
> 请更新至新版

已确认是openssl库在编译的时候使用了windows的加密服务，我已经重新编译了openssl进行了替换。新版还未测试。

**Comment by ugenehan** [comment]
最新版5.6.3已测试过，还是存在这个问题。是由于openssl的lib编译时使用的BCryptGenRandom这个函数。这个是在bcrypt.dll中的。

**Comment by ldcsaa** [comment]
我试过 5.6.4 是没问题的，你也可以自己运行一下 HP-Socket\Windows\Demo\Release\x86 中的 demo。

**Comment by ugenehan** [comment]
> 我试过 5.6.4 是没问题的，你也可以自己运行一下 HP-Socket\Windows\Demo\Release\x86 中的 demo。

可能我用你的openssl库编译其它程序时用到了里面的rand_pool_acquire_entropy这个函数，这个函数里面用到了BCryptGenRandom。我自己编译openssl库是去掉了BCryptGenRandom的使用。

**Comment by ldcsaa** [comment]
问题解决了就好~~
