### ISSUE TITLE
Linux下使用hpsocket5.6后造成mysql无法登录问题。

### ISSUE THREAD

**Issue by wanglovec** [ldcsaa/HP-Socket#96]
在centos7下面使用qt5.9及qtcreator开发程序。
使用hpsocket前程序能正常访问mysql数据库，仅仅引用hpsocket库文件后就造成无法登录mysql数据库。返回错误："SSL connection error: Failed to set ciphers to use QMYSQL: Unable to connect"
请问这是什么原因造成的？

**Comment by ldcsaa** [comment]
hpsocket 5.6 自带的 openssl 版本 为 1.1.1。
看看这些文章对你应该有所帮助：
https://stackoverflow.com/questions/43402892/connect-to-mysql-using-sha2
https://stackoverflow.com/questions/24884834/issue-in-mysql-ssl-connection
https://bugs.mysql.com/bug.php?id=75311
https://bugs.mysql.com/bug.php?id=87121

可能的解决办法：
1、如果用不到HPSocket的SSL功能，可以屏蔽HPSocket的SSL支持，用compile.sh重新编译。
2、MySQL客户端与服务端的连接不启用SSL
3、重新配置MySQL服务器的SSL加密算法，加入与OpenSSL同时支持的算法

**Comment by wanglovec** [comment]
屏蔽HPSocket的SSL支持后正常了。

**Comment by ldcsaa** [comment]
试试dev分支的版本，应该可以正常访问mysql~

**Comment by wanglovec** [comment]
谢谢， 我把用到ssh的部分 去掉 后 再编译OK 了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bruce Liang"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 晚上10:23
收件人: "ldcsaa/HP-Socket"<HP-Socket@noreply.github.com&gt;; 
抄送: "冷暖自知"<50713022@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ldcsaa/HP-Socket] Linux下使用hpsocket5.6后造成mysql无法登录问题。 (#96)




试试dev分支的版本，应该可以正常访问mysql~

**Comment by ldcsaa** [comment]
新版本可以调用 SetSSLCipherList("DEFAULT:!aNULL:!eNULL:!SSLv2") 来支持旧加密算法。
