### ISSUE TITLE
如何设置客户端的缓存池大小？

### ISSUE THREAD

**Issue by andfk33** [ldcsaa/HP-Socket#98]
服务端断点调试时，客户端发送数据一直加入内存中，线程WorkerThreadProc中在DoSendData函数里面触发WSAEWOULDBLOCK错误后事件对象m_evBuffer不再触发消费不过来数据。

**Comment by ldcsaa** [comment]
应用层使用GetPendingDataLength获取积压数据进行流控。

**Comment by andfk33** [comment]
> 应用层使用GetPendingDataLength获取积压数据进行流控。

但是m_evBuffer再也不会setevent了唉，不会再去DoSendData

**Comment by ldcsaa** [comment]
数据都发不出去了，当然不会setevent
