### ISSUE TITLE
能否编译一个易语言 TCP_UDP_ONLY 版的支持库

### ISSUE THREAD

**Issue by QQ2017** [ldcsaa/HP-Socket#99]
我看 TCP_UDP_ONLY 的 DLL 已经有了，能否顺手编译一份动态和静态库，不胜感激~

PS: 我把 HP-Socket-5.7.1-Win-Bin_TCP_UDP_ONLY\Bin\HPSocket4C\x86\static\HPSocket4C.lib 文件改名替换到易语言的 static_lib\Hp_Socket_static.lib 文件，并不能成功静态编译.

**Comment by ldcsaa** [comment]
找群主要
